import test from 'node:test'; import assert from 'node:assert/strict'; import {mkdtemp,writeFile,readFile,mkdir,stat} from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path'; import {spawnSync} from 'node:child_process'; import {createHash} from 'node:crypto';
const exe=new URL('./assemble-owned-release-artifact-graph.mjs',import.meta.url).pathname; const H=x=>createHash('sha256').update(x).digest('hex'); const C=v=>Array.isArray(v)?`[${v.map(C)}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+C(v[k])).join(',')}}`:JSON.stringify(v);
async function fixture(mod={}){const d=await mkdtemp(path.join(os.tmpdir(),'fia-graph-'));const rel=H('release'); const specs=[['release','release','fia.release.v1'],['route','route-manifest','fia.route.v1'],['sbom','sbom','fia.sbom.v1'],['prov','provenance','fia.provenance.v1'],['sig','signature','fia.signature.v1'],['rollback','rollback','fia.rollback.v1']]; const nodes=[];for(const [name,role,schema] of specs){let o={schema,identity:H(name),releaseIdentity:rel,value:name};if(mod.node===name)o={...o,...mod.patch};const b=Buffer.from(C(o)+'\n');const p=`evidence/${name}.json`;await mkdir(path.join(d,'evidence'),{recursive:true});await writeFile(path.join(d,p),b);nodes.push({name,role,path:p,schema,identity:o.identity,releaseIdentity:mod.cross===name?H('other'):rel,sha256:H(b),size:b.length})}
 const edges=[{from:'release',to:'route',type:'contains'},{from:'release',to:'sbom',type:'describes'},{from:'release',to:'prov',type:'derived-from'},{from:'release',to:'sig',type:'signed-by'},{from:'release',to:'rollback',type:'rolls-back-to'}]; if(mod.disconnect)edges.pop(); const req={schema:'fia.owned-release-artifact-graph-request.v1',releaseIdentity:rel,nodes,edges,requiredRoles:['route-manifest','sbom','provenance','signature','rollback'],rollbackNode:'rollback'};await writeFile(path.join(d,'request.json'),C(req)+'\n');return d}
function run(d){return spawnSync(process.execPath,[exe,'--request',path.join(d,'request.json'),'--output',path.join(d,'out.json'),'--exportDir',path.join(d,'oci')],{encoding:'utf8'})}
test('assembles deterministic graph and OCI export',async()=>{const a=await fixture(),b=await fixture();assert.equal(run(a).status,0);assert.equal(run(b).status,0);const x=JSON.parse(await readFile(path.join(a,'out.json'))),y=JSON.parse(await readFile(path.join(b,'out.json')));assert.equal(x.identity,y.identity);assert.equal(x.contentIdentity,y.contentIdentity);assert.equal((await readFile(path.join(a,'oci','index.json'),'utf8')),(await readFile(path.join(b,'oci','index.json'),'utf8')))});
test('rejects cross-release node',async()=>{const d=await fixture({cross:'sbom'});assert.notEqual(run(d).status,0)});
test('rejects modified artifact bytes',async()=>{const d=await fixture();await writeFile(path.join(d,'evidence','sbom.json'),'{}\n');assert.notEqual(run(d).status,0)});
test('rejects disconnected rollback lineage',async()=>{const d=await fixture({disconnect:true});assert.notEqual(run(d).status,0)});
test('rejects duplicate logical identity with different bytes',async()=>{const d=await fixture();const req=JSON.parse(await readFile(path.join(d,'request.json')));req.nodes[2].identity=req.nodes[1].identity;req.nodes[2].schema=req.nodes[1].schema;const p=path.join(d,req.nodes[2].path);const o=JSON.parse(await readFile(p));o.identity=req.nodes[1].identity;o.schema=req.nodes[1].schema;const b=Buffer.from(C(o)+'\n');await writeFile(p,b);req.nodes[2].sha256=H(b);req.nodes[2].size=b.length;await writeFile(path.join(d,'request.json'),C(req)+'\n');assert.notEqual(run(d).status,0)});
test('refuses retained outputs before mutation',async()=>{const d=await fixture();await writeFile(path.join(d,'out.json'),'keep');const r=run(d);assert.notEqual(r.status,0);assert.equal(await readFile(path.join(d,'out.json'),'utf8'),'keep');await assert.rejects(stat(path.join(d,'oci')))});
test('rejects embedded evidence identity mismatch',async()=>{const d=await fixture();const req=JSON.parse(await readFile(path.join(d,'request.json')));req.nodes[1].identity=H('lie');await writeFile(path.join(d,'request.json'),C(req)+'\n');assert.notEqual(run(d).status,0)});
