#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { runStep } from './run-step.mjs';
import { compileBuildRun } from './compile-build-run.mjs';
const PLAN_SCHEMA='fia.build-plan.v1',FAILED_SCHEMA='fia.build-run-failure.v1';
const sha256=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
function sort(v){if(Array.isArray(v))return v.map(sort);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])]));return v}
const canonical=v=>JSON.stringify(sort(v)); function fail(m){throw new Error(m)};
async function readPlan(file){const bytes=await readFile(file);let value;try{value=JSON.parse(bytes)}catch{fail('invalid build plan JSON')}if(value?.schema!==PLAN_SCHEMA||!Array.isArray(value.steps)||value.steps.length===0)fail('unsupported or empty build plan');const names=new Set();for(const [i,s] of value.steps.entries()){if(!s||typeof s!=='object'||!/^[a-z0-9][a-z0-9._-]{0,63}$/.test(s.name||''))fail(`invalid plan step at index ${i}`);if(names.has(s.name))fail(`duplicate plan step: ${s.name}`);names.add(s.name);if(s.required===false)fail(`optional steps are unsupported: ${s.name}`);if(typeof s.command!=='string'||!s.command.trim())fail(`missing command for step: ${s.name}`)}return{value,bytes}}
export async function build({plan,workdir='.',artifacts='artifacts',sourceCommit=null,timeoutMs=300000,maxBytes=1048576,env=process.env}){if(!plan)fail('missing build plan');const planInput=await readPlan(plan);const root=path.resolve(workdir),outRoot=path.resolve(root,artifacts),logsDir=path.join(outRoot,'logs');await mkdir(logsDir,{recursive:true});const logPaths=[];const completed=[];let active=null;try{for(const step of planInput.value.steps){active=step.name;const logPath=path.join(logsDir,`${step.name}.json`);await runStep({name:step.name,command:step.command,cwd:root,output:logPath,timeoutMs:step.timeoutMs??timeoutMs,maxBytes:step.maxBytes??maxBytes,env});logPaths.push(logPath);completed.push(step.name)}const runPath=path.join(outRoot,'build-run.json');const run=await compileBuildRun({plan,logs:logPaths,output:runPath,sourceCommit});return{status:'succeeded',run,runPath}}catch(error){const core={schema:FAILED_SCHEMA,sourceCommit,plan:sha256(Buffer.from(canonical(planInput.value))),planFile:sha256(planInput.bytes),status:'failed',completed,failedStep:active,error:String(error.message||error),logs:logPaths.map(p=>path.relative(root,p))};const record={...core,failure:sha256(Buffer.from(canonical(core)))};const failedPath=path.join(outRoot,'build-run.failed.json');await writeFile(failedPath,canonical(record)+'\n',{flag:'wx',mode:0o600});throw Object.assign(new Error(`fia build failed at ${active}: ${error.message}`),{failedPath,record})}}
function args(argv){const o={};for(let i=0;i<argv.length;i++){const t=argv[i];if(!t.startsWith('--'))fail(`unexpected argument: ${t}`);o[t.slice(2)]=argv[++i]}return{plan:o.plan,workdir:o.workdir??'.',artifacts:o.artifacts??'artifacts',sourceCommit:o.commit??null,timeoutMs:o.timeout,maxBytes:o.maxBytes}}
if(import.meta.url===`file://${process.argv[1]}`)build(args(process.argv.slice(2))).then(v=>console.log(canonical(v))).catch(e=>{console.error(e.message);process.exitCode=1});
