import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,access} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {build} from './build.mjs';
const tmp=()=>mkdtemp(path.join(os.tmpdir(),'fia-build-'));
async function plan(dir,steps){const p=path.join(dir,'plan.json');await writeFile(p,JSON.stringify({schema:'fia.build-plan.v1',steps}));return p}
test('executes exact order and compiles successful run',async()=>{const d=await tmp();const p=await plan(d,[{name:'one',command:'printf one'},{name:'two',command:'printf two'}]);const r=await build({plan:p,workdir:d});assert.equal(r.status,'succeeded');assert.equal(r.preflight.schema,'fia.build-plan-preflight.v1');assert.deepEqual(r.run.steps.map(s=>s.step),['one','two']);});
test('retains failed run and stops later stages',async()=>{const d=await tmp();const marker=path.join(d,'later');const p=await plan(d,[{name:'ok',command:'printf ok'},{name:'bad',command:'exit 7'},{name:'later',command:`touch ${marker}`}]);await assert.rejects(build({plan:p,workdir:d}),/failed at bad/);await assert.rejects(access(marker));const failed=JSON.parse(await readFile(path.join(d,'artifacts/build-run.failed.json')));assert.deepEqual(failed.completed,['ok']);assert.equal(failed.failedStep,'bad');assert.match(failed.preflight,/^sha256:/);});
test('rejects duplicate plan stages before execution',async()=>{const d=await tmp();const p=await plan(d,[{name:'same',command:'true'},{name:'same',command:'true'}]);await assert.rejects(build({plan:p,workdir:d}),/duplicate plan step/);});
test('refuses false success when retained output already exists',async()=>{const d=await tmp();const p=await plan(d,[{name:'one',command:'true'}]);await build({plan:p,workdir:d});await assert.rejects(build({plan:p,workdir:d}));});
test('failed record is immutable',async()=>{const d=await tmp();const p=await plan(d,[{name:'bad',command:'false'}]);await assert.rejects(build({plan:p,workdir:d}));await assert.rejects(build({plan:p,workdir:d}));});
test('rejects provider publication before any command executes',async()=>{const d=await tmp();const marker=path.join(d,'published');const p=await plan(d,[{name:'publish',command:`vercel deploy && touch ${marker}`}]);await assert.rejects(build({plan:p,workdir:d}),/provider-coupling/);await assert.rejects(access(marker));await assert.rejects(access(path.join(d,'artifacts/logs/publish.json')));});
