import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,symlink,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
const exe=new URL('./commit-owned-installation.mjs',import.meta.url).pathname;const sha=b=>createHash('sha256').update(b).digest('hex');const sort=v=>Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;const canon=v=>JSON.stringify(sort(v));const id=o=>sha(Buffer.from(canon(o)));
async function fixture(){const d=await mkdtemp(join(tmpdir(),'fia-commit-')),state=join(d,'state'),rel=join(state,'releases','preview-abc'),runtime=join(rel,'runtime');await mkdir(runtime,{recursive:true});const html=Buffer.from('<html lang="en"><meta name="viewport" content="width=device-width"><body>ok</body></html>');await writeFile(join(runtime,'index.html'),html);await symlink('releases/preview-abc',join(state,'active'));const inv=[{path:'index.html',mode:420,size:html.length,sha256:sha(html)}];let install={schema:'fia.owned-deployment-installation.v1',releaseIdentity:'r'.repeat(64),installedInventory:inv};install={...install,identity:id(install)};let routes={schema:'fia.runtime-route-manifest.v1',routes:[{route:'/',document:'index.html',assets:[]}],offlineFallback:null};routes={...routes,identity:id(routes)};await writeFile(join(d,'install.json'),canon(install));await writeFile(join(d,'routes.json'),canon(routes));return{d,state,runtime,install:join(d,'install.json'),routes:join(d,'routes.json'),out:join(d,'out.json')}}
function run(f){return spawnSync(process.execPath,[exe,'--installation',f.install,'--routeManifest',f.routes,'--stateDir',f.state,'--output',f.out],{encoding:'utf8'})}
test('commits verified active installation',async()=>{const f=await fixture(),r=run(f);assert.equal(r.status,0,r.stderr);const e=JSON.parse(await readFile(f.out));assert.equal(e.checks.routeClosurePresent,true)});
test('equivalent fixtures are deterministic',async()=>{const a=await fixture(),b=await fixture();assert.equal(run(a).status,0);assert.equal(run(b).status,0);assert.equal(JSON.parse(await readFile(a.out)).identity,JSON.parse(await readFile(b.out)).identity)});
test('rejects active pointer escape',async()=>{const f=await fixture();await import('node:fs/promises').then(async fs=>{await fs.unlink(join(f.state,'active'));await fs.symlink(tmpdir(),join(f.state,'active'))});const r=run(f);assert.notEqual(r.status,0)});
test('rejects changed installed bytes',async()=>{const f=await fixture();await writeFile(join(f.runtime,'index.html'),'changed');const r=run(f);assert.notEqual(r.status,0)});
test('rejects missing route closure',async()=>{const f=await fixture(),o=JSON.parse(await readFile(f.routes));delete o.identity;o.routes[0].assets=['app.js'];o.identity=id(o);await writeFile(f.routes,canon(o));assert.notEqual(run(f).status,0)});
test('rejects stale identities',async()=>{const f=await fixture(),o=JSON.parse(await readFile(f.install));o.releaseIdentity='x'.repeat(64);await writeFile(f.install,canon(o));assert.notEqual(run(f).status,0)});
test('preserves existing evidence',async()=>{const f=await fixture();await writeFile(f.out,'keep');assert.notEqual(run(f).status,0);assert.equal(await readFile(f.out,'utf8'),'keep')});
