import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,symlink} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {compilePrivateRootWorkerSpec} from './compile-private-root-worker-spec.mjs';
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'fia-root-')),source=path.join(root,'source'),workspace=path.join(root,'workspace'),bin=path.join(root,'bwrap');await mkdir(source);await mkdir(workspace);await writeFile(path.join(source,'index.js'),'ok');await writeFile(bin,'fake-bwrap');return{root,source,workspace,bin,output:path.join(root,'spec.json')}}
const hooks=f=>({resolveBinary:()=>f.bin,probe:()=>({status:0,stderr:''})});
test('equivalent trees produce identical identities',async()=>{const a=await fixture(),b=await fixture();const x=await compilePrivateRootWorkerSpec({...a,command:['node','index.js']},hooks(a));const y=await compilePrivateRootWorkerSpec({...b,command:['node','index.js']},hooks(b));assert.equal(x.identity,y.identity)});
test('launcher uses private root and no network',async()=>{const f=await fixture();const x=await compilePrivateRootWorkerSpec({...f,command:['node','index.js']},hooks(f));for(const flag of ['--unshare-net','--unshare-pid','--proc','--dev','--tmpfs','--ro-bind','--bind'])assert.ok(x.launcher.includes(flag));assert.equal(x.policy.filesystemRoot,'bubblewrap-private-root')});
test('probe failure rejects admission',async()=>{const f=await fixture();await assert.rejects(()=>compilePrivateRootWorkerSpec({...f,command:['true']},{resolveBinary:()=>f.bin,probe:()=>({status:1,stderr:'denied'})}),/probe failed/)});
test('overlapping mounts are rejected',async()=>{const f=await fixture();await assert.rejects(()=>compilePrivateRootWorkerSpec({...f,command:['true'],readOnly:[{host:f.source,container:'/workspace'}]},hooks(f)),/overlapping/)});
test('symlink in admitted source is rejected',async()=>{const f=await fixture();await symlink('/tmp',path.join(f.source,'escape'));await assert.rejects(()=>compilePrivateRootWorkerSpec({...f,command:['true']},hooks(f)),/symlink/)});
test('existing evidence is preserved',async()=>{const f=await fixture();await writeFile(f.output,'keep');await assert.rejects(()=>compilePrivateRootWorkerSpec({...f,command:['true']},hooks(f)),/already exists/);assert.equal(await readFile(f.output,'utf8'),'keep')});
