import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os'; import path from 'node:path'; import { createHash } from 'node:crypto';
import { createBundle, importBundle } from './bundle-release.mjs'; import { rehearseReleaseImport } from './rehearse-release-import.mjs';
const h=b=>createHash('sha256').update(b).digest('hex');
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'fia-rehearsal-fixture-'));const store=path.join(root,'store');const bytes=Buffer.from('hello\n');const bd=h(bytes);const artifact=`sha256:${h(Buffer.from('artifact'))}`;await mkdir(path.join(store,'blobs','sha256',bd.slice(0,2)),{recursive:true});await writeFile(path.join(store,'blobs','sha256',bd.slice(0,2),bd),bytes);await mkdir(path.join(store,'releases'),{recursive:true});await writeFile(path.join(store,'releases',`${artifact.slice(7)}.json`),JSON.stringify({schema:'fia.release.v1',artifact,files:[{path:'index.html',size:bytes.length,blob:`sha256:${bd}`}]}));const ev=path.join(root,'manifest.json');await writeFile(ev,JSON.stringify({schema:'fia.artifact-manifest.v1'}));const bundle=path.join(root,'release.fia');await createBundle({store,artifact,evidence:[ev],output:bundle});return{root,bundle,artifact};}
test('rehearses independent imports deterministically',async()=>{const f=await fixture();const a=await rehearseReleaseImport({input:f.bundle,attempts:2});const b=await rehearseReleaseImport({input:f.bundle,attempts:3});assert.equal(a.artifact,f.artifact);assert.equal(a.storeInventory.length,2);assert.equal(a.evidenceInventory.length,1);assert.notEqual(a.rehearsal,b.rehearsal);});
test('writes immutable attestation',async()=>{const f=await fixture();const out=path.join(f.root,'attestation.json');const r=await rehearseReleaseImport({input:f.bundle,attempts:2,attestation:out});assert.equal(JSON.parse(await readFile(out,'utf8')).rehearsal,r.rehearsal);await assert.rejects(()=>rehearseReleaseImport({input:f.bundle,attempts:2,attestation:out}),/EEXIST/);});
test('rejects invalid attempt counts before import',async()=>{const f=await fixture();await assert.rejects(()=>rehearseReleaseImport({input:f.bundle,attempts:1}),/attempts/);await assert.rejects(()=>rehearseReleaseImport({input:f.bundle,attempts:9}),/attempts/);});
test('rejects tampered bundles',async()=>{const f=await fixture();const data=JSON.parse(await readFile(f.bundle,'utf8'));data.entries[0].data=Buffer.from('tampered').toString('base64');await writeFile(f.bundle,JSON.stringify(data));await assert.rejects(()=>rehearseReleaseImport({input:f.bundle,attempts:2}),/bundle identity mismatch/);});
test('detects nondeterministic import results',async()=>{const f=await fixture();let n=0;const importer=async args=>{const r=await importBundle(args);n++;if(n===2)await writeFile(path.join(args.store,'nondeterministic.txt'),'drift');return r;};await assert.rejects(()=>rehearseReleaseImport({input:f.bundle,attempts:2,importer}),/import rehearsal mismatch at attempt 2/);});
