import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, readFile, writeFile, symlink } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { runPrivateRootWorker } from './run-private-root-worker.mjs';
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const stable=v=>JSON.stringify(canonical(v));
const sha256=b=>createHash('sha256').update(b).digest('hex');
async function inv(root){const {readdir,lstat,readFile}=await import('node:fs/promises');const out=[];async function walk(d,r=''){for(const n of (await readdir(d)).sort()){const a=path.join(d,n),p=r?`${r}/${n}`:n,s=await lstat(a);if(s.isDirectory()){out.push({path:p,type:'directory',mode:s.mode&511});await walk(a,p)}else{const b=await readFile(a);out.push({path:p,type:'file',mode:s.mode&511,size:b.length,sha256:sha256(b)})}}}await walk(root);return out}
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'fia-run-root-')),source=path.join(root,'source'),workspace=path.join(root,'workspace'),bin=path.join(root,'bwrap'),specPath=path.join(root,'spec.json'),output=path.join(root,'run.json');await mkdir(source);await mkdir(workspace);await writeFile(path.join(source,'index.js'),'ok');await writeFile(bin,'fake-bwrap');const sourceIdentity=sha256(Buffer.from(stable(await inv(source)))),workspaceIdentity=sha256(Buffer.from(stable(await inv(workspace)))),bb=await readFile(bin);const spec={schema:'fia.private-root-worker-spec.v1',policy:{filesystemRoot:'bubblewrap-private-root'},bwrap:{executable:'bwrap',sha256:sha256(bb),bytes:bb.length,probe:'passed'},command:['true'],mounts:{readOnly:[{hostRef:'source',container:'/source',hostType:'directory',inventoryIdentity:sourceIdentity}],writable:[{hostRef:'workspace',container:'/workspace',hostType:'directory',inventoryIdentity:workspaceIdentity}]},launcher:['bwrap','--ro-bind','{source}','/source','--bind','{workspace}','/workspace','--','true']};spec.identity=sha256(Buffer.from(stable(spec)));await writeFile(specPath,`${JSON.stringify(spec,null,2)}\n`);return{root,source,workspace,bin,spec:specPath,output,hostRefs:{source,workspace}}}
const success=async()=>({code:0,signal:null,timedOut:false,executionError:null,stdout:{bytes:2,sha256:sha256(Buffer.from('ok')),truncated:false,text:'ok'},stderr:{bytes:0,sha256:sha256(Buffer.alloc(0)),truncated:false,text:''}});
const hooks=f=>({resolveBinary:()=>f.bin,execute:success});
test('equivalent runs produce identical identities',async()=>{const a=await fixture(),b=await fixture();const x=await runPrivateRootWorker(a,hooks(a)),y=await runPrivateRootWorker(b,hooks(b));assert.equal(x.identity,y.identity)});
test('specification substitution is rejected',async()=>{const f=await fixture(),s=JSON.parse(await readFile(f.spec,'utf8'));s.policy.changed=true;await writeFile(f.spec,JSON.stringify(s));await assert.rejects(()=>runPrivateRootWorker(f,hooks(f)),/identity mismatch/)});
test('bubblewrap executable drift is rejected',async()=>{const f=await fixture();await writeFile(f.bin,'changed');await assert.rejects(()=>runPrivateRootWorker(f,hooks(f)),/executable drift/)});
test('mount content drift is rejected',async()=>{const f=await fixture();await writeFile(path.join(f.source,'index.js'),'changed');await assert.rejects(()=>runPrivateRootWorker(f,hooks(f)),/mount inventory drift/)});
test('timeout retains evidence and fails',async()=>{const f=await fixture();const execute=async()=>({code:null,signal:'SIGKILL',timedOut:true,executionError:null,stdout:{bytes:0,sha256:sha256(Buffer.alloc(0)),truncated:false,text:''},stderr:{bytes:0,sha256:sha256(Buffer.alloc(0)),truncated:false,text:''}});await assert.rejects(()=>runPrivateRootWorker(f,{resolveBinary:()=>f.bin,execute}),/timed-out/);const r=JSON.parse(await readFile(f.output,'utf8'));assert.equal(r.result.status,'timed-out')});
test('nonzero exit retains failure evidence',async()=>{const f=await fixture();const execute=async()=>({code:7,signal:null,timedOut:false,executionError:null,stdout:{bytes:0,sha256:sha256(Buffer.alloc(0)),truncated:false,text:''},stderr:{bytes:0,sha256:sha256(Buffer.alloc(0)),truncated:false,text:''}});await assert.rejects(()=>runPrivateRootWorker(f,{resolveBinary:()=>f.bin,execute}),/failed/);assert.equal(JSON.parse(await readFile(f.output,'utf8')).result.code,7)});
test('symlink contamination in workspace is rejected',async()=>{const f=await fixture();await symlink('/tmp',path.join(f.workspace,'escape'));await assert.rejects(()=>runPrivateRootWorker(f,hooks(f)),/symlink/)});
test('existing evidence is preserved',async()=>{const f=await fixture();await writeFile(f.output,'keep');await assert.rejects(()=>runPrivateRootWorker(f,hooks(f)),/already exists/);assert.equal(await readFile(f.output,'utf8'),'keep')});
