import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, chmod, lstat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { runCleanEnvironmentBuild } from './run-clean-environment-build.mjs';
const sha256=v=>`sha256:${createHash('sha256').update(v).digest('hex')}`;
function sort(v){if(Array.isArray(v))return v.map(sort);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])]));return v;}
const canonical=v=>JSON.stringify(sort(v));
async function fixture(){
 const root=await mkdtemp(path.join(os.tmpdir(),'fia-ceb-test-'));await mkdir(path.join(root,'src'));await writeFile(path.join(root,'package-lock.json'),'lock\n');await writeFile(path.join(root,'src','build.mjs'),"import {mkdir,readFile,writeFile} from 'node:fs/promises'; await mkdir('dist'); const d=await readFile('node_modules/pkg/index.js'); await writeFile('dist/out.txt',d);\n");await chmod(path.join(root,'src','build.mjs'),0o755);
 const files=[];for(const rel of ['package-lock.json','src/build.mjs']){const bytes=await readFile(path.join(root,rel)),st=await lstat(path.join(root,rel));files.push({path:rel,bytes:bytes.length,sha256:sha256(bytes),mode:st.mode&0o777});}files.sort((a,b)=>a.path.localeCompare(b.path));const core={schema:'fia.build-input-manifest.v1',files};const manifest={...core,manifest:sha256(Buffer.from(canonical(core)))};const manifestPath=path.join(root,'manifest.json');await writeFile(manifestPath,canonical(manifest));
 const lockIdentity=sha256(await readFile(path.join(root,'package-lock.json'))),cacheCore={schema:'fia.owned-npm-cache-manifest.v1',lockfile:lockIdentity,packages:[]},cache={...cacheCore,manifest:sha256(Buffer.from(canonical(cacheCore)))},cachePath=path.join(root,'cache.json'),cacheDir=path.join(root,'cache');await writeFile(cachePath,canonical(cache));await mkdir(cacheDir);return{root,manifestPath,cachePath,cacheDir,cache};
}
function installerFactory({mutateInstall=false}={}){let n=0;return async({workspace,attestation,lockfile,cacheManifest})=>{n++;await mkdir(path.join(workspace,'node_modules','pkg'),{recursive:true});await writeFile(path.join(workspace,'node_modules','pkg','index.js'),mutateInstall&&n===2?'different':'owned');const target=path.join(workspace,'node_modules','pkg','index.js'),bytes=await readFile(target),st=await lstat(target),inventory=[{path:'pkg/index.js',bytes:bytes.length,sha256:sha256(bytes),mode:st.mode&0o777}],cache=JSON.parse(await readFile(cacheManifest)),lock=sha256(await readFile(path.join(workspace,lockfile))),core={schema:'fia.owned-npm-dependency-installation.v1',lockfile:lock,cacheManifest:cache.manifest,inventory,status:'installed-offline'},record={...core,attestation:sha256(Buffer.from(canonical(core)))};await writeFile(attestation,canonical(record));return record;};}
async function execute(overrides={}){const f=await fixture(),result=await runCleanEnvironmentBuild({source:f.root,manifest:f.manifestPath,lockfile:'package-lock.json',cacheManifest:f.cachePath,cacheDir:f.cacheDir,command:'node src/build.mjs',outputDir:'dist',attempts:2,attestation:path.join(f.root,'att.json'),installer:installerFactory(),...overrides});return{f,result};}
test('binds dependency and output inventories reproducibly',async()=>{const {result}=await execute();assert.equal(result.status,'reproducible-clean-environment');assert.equal(result.attemptEvidence.length,2);assert.equal(result.outputInventory[0].path,'out.txt');});
test('rejects dependency mutation by build',async()=>{const f=await fixture();await assert.rejects(()=>runCleanEnvironmentBuild({source:f.root,manifest:f.manifestPath,cacheManifest:f.cachePath,cacheDir:f.cacheDir,command:"node -e \"require('fs').writeFileSync('node_modules/pkg/index.js','changed');require('fs').mkdirSync('dist');require('fs').writeFileSync('dist/out','x')\"",outputDir:'dist',attestation:path.join(f.root,'a.json'),installer:installerFactory()}),/build mutated dependency tree/);});
test('rejects divergent dependency installations',async()=>{const f=await fixture();await assert.rejects(()=>runCleanEnvironmentBuild({source:f.root,manifest:f.manifestPath,cacheManifest:f.cachePath,cacheDir:f.cacheDir,command:'node src/build.mjs',outputDir:'dist',attestation:path.join(f.root,'a.json'),installer:installerFactory({mutateInstall:true})}),/dependency mismatch/);});
test('rejects divergent application output',async()=>{const f=await fixture();await assert.rejects(()=>runCleanEnvironmentBuild({source:f.root,manifest:f.manifestPath,cacheManifest:f.cachePath,cacheDir:f.cacheDir,command:"node -e \"require('fs').mkdirSync('dist');require('fs').writeFileSync('dist/out',Math.random().toString())\"",outputDir:'dist',attestation:path.join(f.root,'a.json'),installer:installerFactory()}),/application output mismatch/);});
test('rejects cache manifest for another lockfile',async()=>{const f=await fixture(),bad={...f.cache,lockfile:sha256(Buffer.from('other'))};delete bad.manifest;bad.manifest=sha256(Buffer.from(canonical(bad)));await writeFile(f.cachePath,canonical(bad));await assert.rejects(()=>runCleanEnvironmentBuild({source:f.root,manifest:f.manifestPath,cacheManifest:f.cachePath,cacheDir:f.cacheDir,command:'node src/build.mjs',outputDir:'dist',attestation:path.join(f.root,'a.json'),installer:installerFactory()}),/lockfile identity mismatch/);});
test('retained attestation cannot be overwritten',async()=>{const {f}=await execute();await assert.rejects(()=>runCleanEnvironmentBuild({source:f.root,manifest:f.manifestPath,cacheManifest:f.cachePath,cacheDir:f.cacheDir,command:'node src/build.mjs',outputDir:'dist',attestation:path.join(f.root,'att.json'),installer:installerFactory()}),/EEXIST/);});
