import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {runCgroupPrivateRootWorker} from './run-cgroup-private-root-worker.mjs';
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;const stable=v=>JSON.stringify(canonical(v));const sha=b=>createHash('sha256').update(b).digest('hex');
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'fia-cg-')),source=path.join(root,'source'),workspace=path.join(root,'workspace'),bin=path.join(root,'bwrap');await mkdir(source);await mkdir(workspace);await writeFile(path.join(source,'index.txt'),'source');await writeFile(path.join(workspace,'input.txt'),'input');await writeFile(bin,'fake');const inv=async d=>{const names=(await import('node:fs/promises')).readdir(d);const out=[];for(const n of (await names).sort()){const b=await readFile(path.join(d,n));out.push({path:n,type:'file',mode:0o644,size:b.length,sha256:sha(b)})}return out};const spec={schema:'fia.private-root-worker-spec.v1',policy:{},bwrap:{executable:'bwrap',sha256:sha(await readFile(bin)),bytes:4,probe:'passed'},command:['true'],mounts:{readOnly:[{hostRef:'source',container:'/source',hostType:'directory',inventoryIdentity:sha(Buffer.from(stable(await inv(source))))}],writable:[{hostRef:'workspace',container:'/workspace',hostType:'directory',inventoryIdentity:sha(Buffer.from(stable(await inv(workspace))))}]},launcher:['bwrap','--ro-bind','{source}','/source','--bind','{workspace}','/workspace','--','true']};spec.identity=sha(Buffer.from(stable(spec)));const specPath=path.join(root,'spec.json');await writeFile(specPath,JSON.stringify(spec));return{root,source,workspace,bin,specPath}}
function cg({remaining=[]}={}){return{controllers:['cpu','memory','pids'],attached:null,killed:false,cleaned:false,async attach(pid){this.attached=pid},async kill(){this.killed=true},async procs(){return remaining},async cleanup(){this.cleaned=true}}}
const okRun={code:0,signal:null,timedOut:false,executionError:null,stdout:{bytes:0,sha256:sha(Buffer.alloc(0)),truncated:false,text:''},stderr:{bytes:0,sha256:sha(Buffer.alloc(0)),truncated:false,text:''}};
async function run(f,out,extra={}){const c=extra.cgroup??cg();return runCgroupPrivateRootWorker({spec:f.specPath,hostRefs:{source:f.source,workspace:f.workspace},output:out,cgroupRoot:'/fake',memoryMax:'1024',cpuMax:'1000 10000',pidsMax:'8',timeoutMs:1000,logLimitBytes:1024},{resolveBinary:()=>f.bin,createCgroup:async()=>c,execute:extra.execute??(async(_cmd,o)=>{await o.cgroup.attach(123);return structuredClone(okRun)})})}
test('equivalent runs are deterministic',async()=>{const a=await fixture(),b=await fixture();const ra=await run(a,path.join(a.root,'a.json')),rb=await run(b,path.join(b.root,'b.json'));assert.equal(ra.identity,rb.identity)});
test('rejects stale spec identity',async()=>{const f=await fixture(),s=JSON.parse(await readFile(f.specPath));s.command=['false'];await writeFile(f.specPath,JSON.stringify(s));await assert.rejects(()=>run(f,path.join(f.root,'o.json')),/identity mismatch/)});
test('rejects mount drift',async()=>{const f=await fixture();await writeFile(path.join(f.source,'index.txt'),'changed');await assert.rejects(()=>run(f,path.join(f.root,'o.json')),/mount inventory drift/)});
test('rejects executable drift',async()=>{const f=await fixture();await writeFile(f.bin,'other');await assert.rejects(()=>run(f,path.join(f.root,'o.json')),/executable drift/)});
test('fails when cgroup retains processes',async()=>{const f=await fixture();await assert.rejects(()=>run(f,path.join(f.root,'o.json'),{cgroup:cg({remaining:['999']})}),/worker failed/);const r=JSON.parse(await readFile(path.join(f.root,'o.json')));assert.deepEqual(r.cgroup.remainingProcesses,['999']);assert.equal(r.result.status,'failed')});
test('retains timeout evidence',async()=>{const f=await fixture();await assert.rejects(()=>run(f,path.join(f.root,'o.json'),{execute:async()=>({...okRun,timedOut:true,signal:'SIGKILL'})}),/worker timed-out/);const r=JSON.parse(await readFile(path.join(f.root,'o.json')));assert.equal(r.result.status,'timed-out')});
test('refuses evidence overwrite',async()=>{const f=await fixture(),o=path.join(f.root,'o.json');await writeFile(o,'keep');await assert.rejects(()=>run(f,o),/destination already exists/);assert.equal(await readFile(o,'utf8'),'keep')});
