import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { runHardenedLinuxWorker } from './run-hardened-linux-worker.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}const stable=v=>JSON.stringify(canonical(v));
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'fia-run-'));const workspace=path.join(root,'ws');await mkdir(workspace);await writeFile(path.join(workspace,'input.txt'),'x');const fake={sha256:'a'.repeat(64),bytes:1};const plan={schema:'fia.hardened-linux-worker-plan.v1',policy:{filesystemRoot:'not-chrooted',cgroupV2:'not-configured'},limits:{timeoutMs:1000},command:{executable:'node',args:[]},executables:{unshare:fake,prlimit:fake,command:fake},launcher:['unshare','--','true']};plan.identity=sha(Buffer.from(stable(plan)));const planPath=path.join(root,'plan.json');await writeFile(planPath,JSON.stringify(plan));return{root,workspace,planPath};}
const verify=async()=>'/fake';
test('equivalent successful runs are deterministic',async()=>{const a=await fixture(),b=await fixture();const exec=async(_l,{stdout})=>{stdout.push(Buffer.from('ok'));return{exitCode:0,signal:null,timedOut:false,error:null};};const ra=await runHardenedLinuxWorker({plan:a.planPath,workspace:a.workspace,output:path.join(a.root,'out.json')},{verifyExecutable:verify,execute:exec});const rb=await runHardenedLinuxWorker({plan:b.planPath,workspace:b.workspace,output:path.join(b.root,'out.json')},{verifyExecutable:verify,execute:exec});assert.equal(ra.identity,rb.identity);});
test('plan identity substitution is rejected',async()=>{const f=await fixture();const p=JSON.parse(await readFile(f.planPath));p.limits.timeoutMs=2;await writeFile(f.planPath,JSON.stringify(p));await assert.rejects(()=>runHardenedLinuxWorker({plan:f.planPath,workspace:f.workspace,output:path.join(f.root,'o.json')},{verifyExecutable:verify}),/identity mismatch/);});
test('executable drift is rejected',async()=>{const f=await fixture();await assert.rejects(()=>runHardenedLinuxWorker({plan:f.planPath,workspace:f.workspace,output:path.join(f.root,'o.json')},{verifyExecutable:async()=>{throw new Error('executable identity mismatch: unshare');}}),/executable identity mismatch/);});
test('timeout retains evidence and fails',async()=>{const f=await fixture();const out=path.join(f.root,'o.json');await assert.rejects(()=>runHardenedLinuxWorker({plan:f.planPath,workspace:f.workspace,output:out},{verifyExecutable:verify,execute:async()=>({exitCode:null,signal:'SIGKILL',timedOut:true,error:null})}),/timed-out/);const r=JSON.parse(await readFile(out));assert.equal(r.status,'timed-out');});
test('nonzero exit retains failed evidence',async()=>{const f=await fixture();const out=path.join(f.root,'o.json');await assert.rejects(()=>runHardenedLinuxWorker({plan:f.planPath,workspace:f.workspace,output:out},{verifyExecutable:verify,execute:async()=>({exitCode:7,signal:null,timedOut:false,error:null})}),/failed/);assert.equal(JSON.parse(await readFile(out)).result.exitCode,7);});
test('symlink workspace contamination is rejected',async()=>{const f=await fixture();const {symlink}=await import('node:fs/promises');await symlink('/tmp',path.join(f.workspace,'escape'));await assert.rejects(()=>runHardenedLinuxWorker({plan:f.planPath,workspace:f.workspace,output:path.join(f.root,'o.json')},{verifyExecutable:verify}),/symlink/);});
test('existing evidence cannot be overwritten',async()=>{const f=await fixture();const out=path.join(f.root,'o.json');await writeFile(out,'keep');await assert.rejects(()=>runHardenedLinuxWorker({plan:f.planPath,workspace:f.workspace,output:out},{verifyExecutable:verify}),/already exists/);assert.equal(await readFile(out,'utf8'),'keep');});
