import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,createHash} from 'node:crypto';import {promises as fs} from 'node:fs';import os from 'node:os';import path from 'node:path';import {sealPortableRuntimeBundle,promoteSealedRuntime,rollbackRelease} from './seal-and-promote-runtime.mjs';
const hash=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;const stable=v=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`:JSON.stringify(v);const id=v=>hash(Buffer.from(stable(v)));
async function tmp(){return fs.mkdtemp(path.join(os.tmpdir(),'fia-promote-'))}
function keys(){const {privateKey,publicKey}=generateKeyPairSync('ed25519');return{privateKey:privateKey.export({type:'pkcs8',format:'pem'}),publicKey:publicKey.export({type:'spki',format:'pem'})}}
async function bundle(root,name,text){const dir=path.join(root,name);await fs.mkdir(path.join(dir,'objects/sha256'),{recursive:true});const html=Buffer.from(`<!doctype html><html lang="en"><head><title>${name}</title></head><body><main><h1>${text}</h1></main></body></html>`);const h=hash(html);const obj=`objects/sha256/${h.slice(7,9)}/${h.slice(9)}`;await fs.mkdir(path.dirname(path.join(dir,obj)),{recursive:true});await fs.writeFile(path.join(dir,obj),html);const launcher=Buffer.from(`#!/usr/bin/env node\nimport{createServer}from'node:http';import{promises as fs}from'node:fs';import path from'node:path';const m=JSON.parse(await fs.readFile('bundle-manifest.json'));const a=m.artifacts[process.argv.includes('rollback')?'rollback':'current'];const s=createServer(async(q,r)=>{const f=a.files[0];r.writeHead(200);r.end(await fs.readFile(path.join('.',f.object)))});const i=process.argv.indexOf('--port');s.listen(Number(process.argv[i+1]),'127.0.0.1',()=>console.log(JSON.stringify({schema:'fia.portable-runtime-start.v1',target:'current',host:'127.0.0.1',port:s.address().port,bundle:m.bundle})));process.on('SIGTERM',()=>s.close());`);await fs.writeFile(path.join(dir,'run.mjs'),launcher,{mode:0o755});const artifact={files:[{path:'index.html',bytes:html.length,mode:0o644,sha256:h,object:obj}],routes:[{route:'/',path:'index.html'}],inventory:id([{path:'index.html',bytes:html.length,mode:0o644,sha256:h}])};const core={schema:'fia.portable-runtime-bundle.v1',policy:{historyFallback:false},artifacts:{current:artifact,rollback:artifact},launcher:{path:'run.mjs',sha256:hash(launcher)}};const manifest={...core,bundle:id(core)};await fs.writeFile(path.join(dir,'bundle-manifest.json'),`${stable(manifest)}\n`);return dir}
test('stable sealing and signature verification',async()=>{const r=await tmp();try{const b=await bundle(r,'b','one'),k=keys();const s=await sealPortableRuntimeBundle({bundle:b,...k,seal:path.join(r,'seal.json')});assert.equal(s.schema,'fia.portable-runtime-bundle-seal.v1');assert.match(s.signature,/^[A-Za-z0-9+/]+=*$/)}finally{await fs.rm(r,{recursive:true,force:true})}});
test('tampered bundle is rejected before promotion',async()=>{const r=await tmp();try{const b=await bundle(r,'b','one'),k=keys(),seal=path.join(r,'seal.json');await sealPortableRuntimeBundle({bundle:b,...k,seal});const m=JSON.parse(await fs.readFile(path.join(b,'bundle-manifest.json')));await fs.writeFile(path.join(b,m.artifacts.current.files[0].object),'bad');await assert.rejects(()=>promoteSealedRuntime({bundle:b,seal,publicKey:k.publicKey,store:path.join(r,'store'),evidence:path.join(r,'p.json')}),/object identity mismatch|sealed inventory mismatch/)}finally{await fs.rm(r,{recursive:true,force:true})}});
test('promotes only after health and atomically retains pointer',async()=>{const r=await tmp();try{const b=await bundle(r,'b','one'),k=keys(),seal=path.join(r,'seal.json');await sealPortableRuntimeBundle({bundle:b,...k,seal});const p=await promoteSealedRuntime({bundle:b,seal,publicKey:k.publicKey,store:path.join(r,'store'),evidence:path.join(r,'p.json')});const current=JSON.parse(await fs.readFile(path.join(r,'store/pointers/current.json')));assert.equal(current.release,p.release);assert.equal(p.health.status,200)}finally{await fs.rm(r,{recursive:true,force:true})}});
test('second promotion retains previous and rollback health checks prior release',async()=>{const r=await tmp();try{const k=keys(),store=path.join(r,'store');for(const [n,t] of [['a','one'],['b','two']]){const b=await bundle(r,n,t),seal=path.join(r,`${n}.seal`);await sealPortableRuntimeBundle({bundle:b,...k,seal});await promoteSealedRuntime({bundle:b,seal,publicKey:k.publicKey,store,evidence:path.join(r,`${n}.promotion`)})}const before=JSON.parse(await fs.readFile(path.join(store,'pointers/current.json')));const rb=await rollbackRelease({store,evidence:path.join(r,'rollback.json')});const after=JSON.parse(await fs.readFile(path.join(store,'pointers/current.json')));assert.notEqual(after.release,before.release);assert.equal(after.release,rb.release);assert.equal(rb.health.status,200)}finally{await fs.rm(r,{recursive:true,force:true})}});
test('wrong public key rejects valid seal',async()=>{const r=await tmp();try{const b=await bundle(r,'b','one'),k=keys(),wrong=keys(),seal=path.join(r,'seal');await sealPortableRuntimeBundle({bundle:b,...k,seal});await assert.rejects(()=>promoteSealedRuntime({bundle:b,seal,publicKey:wrong.publicKey,store:path.join(r,'store'),evidence:path.join(r,'p')}),/public key mismatch/)}finally{await fs.rm(r,{recursive:true,force:true})}});
test('retained evidence cannot be overwritten',async()=>{const r=await tmp();try{const b=await bundle(r,'b','one'),k=keys(),seal=path.join(r,'seal'),e=path.join(r,'p');await sealPortableRuntimeBundle({bundle:b,...k,seal});await fs.writeFile(e,'retained');await assert.rejects(()=>promoteSealedRuntime({bundle:b,seal,publicKey:k.publicKey,store:path.join(r,'store'),evidence:e}),/evidence exists/)}finally{await fs.rm(r,{recursive:true,force:true})}});
