import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { inspectCommand, validateBuildPlan } from './validate-build-plan.mjs';
const tmp=()=>mkdtemp(path.join(os.tmpdir(),'fia-plan-preflight-'));
async function fixture(steps,scripts={}){const dir=await tmp();const plan=path.join(dir,'plan.json');const packageJson=path.join(dir,'package.json');await writeFile(plan,JSON.stringify({schema:'fia.build-plan.v1',steps}));await writeFile(packageJson,JSON.stringify({scripts}));return{dir,plan,packageJson};}

test('accepts immutable commands and resolves nested scripts deterministically',async()=>{const f=await fixture([{name:'deps',command:'npm ci --ignore-scripts'},{name:'compile',command:'npm run build'}],{build:'npm run compile && npm run verify',compile:'vite build',verify:'node verify.mjs'});const a=await validateBuildPlan({plan:f.plan,packageJson:f.packageJson});const b=await validateBuildPlan({plan:f.plan,packageJson:f.packageJson});assert.equal(a.preflight,b.preflight);assert.equal(a.schema,'fia.build-plan-preflight.v2');assert.deepEqual(a.resolvedScripts[0].scripts.map(x=>x.name),['build','compile','verify']);});
test('rejects hosted provider coupling before execution',()=>{for(const command of ['vercel deploy','wrangler pages deploy dist','npm run deploy:cloudflare','gh-pages -d dist'])assert.ok(inspectCommand(command).some(x=>x.code==='provider-coupling'));});
test('rejects network and publication commands',()=>{for(const command of ['curl https://example.invalid/x','git push origin preview','docker push registry/image','kubectl apply -f release.yaml'])assert.ok(inspectCommand(command).some(x=>['network-command','publication-command'].includes(x.code)));});
test('rejects mutable package installation and package executors',()=>{for(const command of ['npm install','npm i vite','pnpm add react','pnpm install','yarn install','npx vite build'])assert.ok(inspectCommand(command).some(x=>['mutable-dependency-command','mutable-package-executor'].includes(x.code)));assert.equal(inspectCommand('pnpm install --frozen-lockfile --offline').length,0);assert.equal(inspectCommand('yarn install --immutable --offline').length,0);});
test('rejects dynamic shell expansion',()=>{for(const command of ['echo $(cat token)','echo `hostname`','echo ${!secret}'])assert.ok(inspectCommand(command).some(x=>x.code==='dynamic-shell-expansion'));});
test('rejects provider coupling hidden behind nested aliases',async()=>{const f=await fixture([{name:'compile',command:'npm run build'}],{build:'npm run package',package:'npx vercel'});await assert.rejects(()=>validateBuildPlan({plan:f.plan,packageJson:f.packageJson}),/package script rejected: package/);});
test('rejects implicit pre and post lifecycle hooks',async()=>{const f=await fixture([{name:'compile',command:'npm run build'}],{prebuild:'curl https://example.invalid',build:'vite build'});await assert.rejects(()=>validateBuildPlan({plan:f.plan,packageJson:f.packageJson}),/unauthorized lifecycle hook: prebuild/);});
test('rejects recursive script cycles and missing aliases',async()=>{const cycle=await fixture([{name:'compile',command:'npm run a'}],{a:'npm run b',b:'npm run a'});await assert.rejects(()=>validateBuildPlan({plan:cycle.plan,packageJson:cycle.packageJson}),/script cycle/);const missing=await fixture([{name:'compile',command:'npm run absent'}],{});await assert.rejects(()=>validateBuildPlan({plan:missing.plan,packageJson:missing.packageJson}),/missing package script/);});
test('binds exact package file and script graph into evidence',async()=>{const f=await fixture([{name:'compile',command:'npm run build'}],{build:'vite build'});const a=await validateBuildPlan({plan:f.plan,packageJson:f.packageJson});await writeFile(f.packageJson,JSON.stringify({name:'changed',scripts:{build:'vite build'}}));const b=await validateBuildPlan({plan:f.plan,packageJson:f.packageJson});assert.notEqual(a.packageFile,b.packageFile);assert.notEqual(a.preflight,b.preflight);});
test('retains accepted evidence immutably',async()=>{const f=await fixture([{name:'compile',command:'node tools/build.mjs'}]);const output=path.join(f.dir,'preflight.json');await validateBuildPlan({plan:f.plan,packageJson:f.packageJson,output});const saved=JSON.parse(await readFile(output));assert.equal(saved.schema,'fia.build-plan-preflight.v2');await assert.rejects(validateBuildPlan({plan:f.plan,packageJson:f.packageJson,output}));});
