import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { main } from './verify-live-deployment-commit.mjs';
const H=b=>createHash('sha256').update(b).digest('hex');
const html=id=>Buffer.from(`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width"></head><body>${id}</body></html>`);
async function server(listenerId,body,{badHeader=false,missingHtml=false}={}){const s=createServer((req,res)=>{if(req.url==='/missing.js'){res.writeHead(missingHtml?200:404,{'content-type':missingHtml?'text/html':'text/plain','x-fia-content-sha256':H(missingHtml?body:Buffer.from('missing')),'x-fia-listener-id':listenerId});res.end(missingHtml?body:'missing');return}const bytes=body;res.writeHead(200,{'content-type':'text/html','content-security-policy':"default-src 'self'",'referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','x-fia-content-sha256':badHeader?'0'.repeat(64):H(bytes),'x-fia-listener-id':listenerId});res.end(bytes)});await new Promise(r=>s.listen(0,'127.0.0.1',r));return {s,url:`http://127.0.0.1:${s.address().port}`}}
function route(release,listener,url,body){return {schema:'fia.owned-listener-route.v1',releaseIdentity:release,listenerId:listener,contentSha256:H(body),host:'127.0.0.1',port:Number(new URL(url).port)}}
function probes(body){return [{path:'/',kind:'route',status:200,mime:'text/html',sha256:H(body)}]}
async function fixture(opts={}){const dir=await mkdtemp(path.join(os.tmpdir(),'fia-live-'));const relA='a'.repeat(64),relB='b'.repeat(64);const oldBody=html('old'),newBody=html('new');const old=await server('old-listener',oldBody);const neu=await server('new-listener',newBody,opts);const previous={baseUrl:old.url,route:route(relA,'old-listener',old.url,oldBody),probes:probes(oldBody)};const candidate={baseUrl:neu.url,route:route(relB,'new-listener',neu.url,newBody)};const req={schema:'fia.owned-live-deployment-commit-request.v1',releaseIdentity:relB,candidate,previous,probes:probes(newBody),missingAssetPath:'/missing.js',timeoutMs:1000,maxResponseBytes:1024*1024};const request=path.join(dir,'request.json'),state=path.join(dir,'route.json'),output=path.join(dir,'out.json');await writeFile(request,JSON.stringify(req));await writeFile(state,JSON.stringify(previous.route));return {dir,old,neu,req,request,state,output}}
async function close(f){await Promise.all([new Promise(r=>f.old.s.close(r)),new Promise(r=>f.neu.s.close(r))]);await rm(f.dir,{recursive:true,force:true})}
test('commits verified live candidate and emits deterministic evidence',async()=>{const f=await fixture();try{const e=await main(['--request',f.request,'--routeState',f.state,'--output',f.output]);assert.equal(e.schema,'fia.owned-live-deployment-commit.v1');assert.equal(JSON.parse(await readFile(f.state)).listenerId,'new-listener');assert.equal(JSON.parse(await readFile(f.output)).identity,e.identity)}finally{await close(f)}});
test('equivalent runs separate deterministic content from operational identity',async()=>{const a=await fixture(),b=await fixture();try{const ea=await main(['--request',a.request,'--routeState',a.state,'--output',a.output]);const eb=await main(['--request',b.request,'--routeState',b.state,'--output',b.output]);assert.equal(ea.contentIdentity,eb.contentIdentity);assert.notEqual(ea.identity,eb.identity)}finally{await close(a);await close(b)}});
test('served-byte mismatch fails before route switch',async()=>{const f=await fixture();try{f.req.probes[0].sha256='c'.repeat(64);await writeFile(f.request,JSON.stringify(f.req));await assert.rejects(main(['--request',f.request,'--routeState',f.state,'--output',f.output]),/served byte mismatch/);assert.equal(JSON.parse(await readFile(f.state)).listenerId,'old-listener')}finally{await close(f)}});
test('dishonest digest header fails closed',async()=>{const f=await fixture({badHeader:true});try{await assert.rejects(main(['--request',f.request,'--routeState',f.state,'--output',f.output]),/digest header mismatch/);assert.equal(JSON.parse(await readFile(f.state)).listenerId,'old-listener')}finally{await close(f)}});
test('SPA masking of missing asset is rejected',async()=>{const f=await fixture({missingHtml:true});try{await assert.rejects(main(['--request',f.request,'--routeState',f.state,'--output',f.output]),/missing asset did not return 404/);assert.equal(JSON.parse(await readFile(f.state)).listenerId,'old-listener')}finally{await close(f)}});
test('stale route state is rejected',async()=>{const f=await fixture();try{const stale={...f.req.previous.route,listenerId:'substituted'};await writeFile(f.state,JSON.stringify(stale));await assert.rejects(main(['--request',f.request,'--routeState',f.state,'--output',f.output]),/stale route state/)}finally{await close(f)}});
test('existing evidence blocks all mutation',async()=>{const f=await fixture();try{await writeFile(f.output,'retained');await assert.rejects(main(['--request',f.request,'--routeState',f.state,'--output',f.output]),/output already exists/);assert.equal(JSON.parse(await readFile(f.state)).listenerId,'old-listener');assert.equal(await readFile(f.output,'utf8'),'retained')}finally{await close(f)}});
