import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const exe = new URL('./verify-owned-release-artifact-graph-restore.mjs', import.meta.url).pathname;
const H = x => createHash('sha256').update(x).digest('hex');
const C = v => Array.isArray(v) ? `[${v.map(C).join(',')}]` : v && typeof v === 'object' ? `{${Object.keys(v).sort().map(k => `${JSON.stringify(k)}:${C(v[k])}`).join(',')}}` : JSON.stringify(v);
async function fixture(mutator) {
  const d = await mkdtemp(path.join(os.tmpdir(), 'fia-graph-restore-')); const oci = path.join(d, 'oci'); await mkdir(path.join(oci, 'blobs', 'sha256'), {recursive:true});
  const rel=H('release'); const specs=[['release','release','fia.release.v1'],['rollback','rollback','fia.rollback.v1'],['sig','signature','fia.signature.v1']]; const nodes=[]; const layers=[];
  for(const [name,role,schema] of specs){const obj={schema,identity:H(name),releaseIdentity:rel,value:name};const bytes=Buffer.from(C(obj)+'\n');const artifactSha256=H(bytes);const nodeId=H(Buffer.from(C({schema,identity:obj.identity,artifactSha256,size:bytes.length,role,releaseIdentity:rel})));nodes.push({name,role,path:`evidence/${name}.json`,schema,identity:obj.identity,releaseIdentity:rel,sha256:artifactSha256,size:bytes.length,nodeId,artifactSha256,artifactSize:bytes.length,sourcePath:`evidence/${name}.json`});layers.push({mediaType:'application/vnd.fia.artifact.v1+json',digest:`sha256:${artifactSha256}`,size:bytes.length,annotations:{'org.opencontainers.image.title':name,'fia.role':role,'fia.node.id':nodeId}});await writeFile(path.join(oci,'blobs','sha256',artifactSha256),bytes)}
  const edges=[{from:nodes[0].nodeId,to:nodes[1].nodeId,type:'rolls-back-to'},{from:nodes[0].nodeId,to:nodes[2].nodeId,type:'signed-by'}]; const contentIdentity=H(Buffer.from(C({releaseIdentity:rel,nodes:nodes.map(n=>({nodeId:n.nodeId,role:n.role,schema:n.schema,identity:n.identity,artifactSha256:n.artifactSha256,artifactSize:n.artifactSize})),edges,rollbackNodeId:nodes[1].nodeId})));const graph={schema:'fia.owned-release-artifact-graph.v1',releaseIdentity:rel,contentIdentity,nodes,edges,rootNodeId:nodes[0].nodeId,rollbackNodeId:nodes[1].nodeId,policy:{completeReachability:true,exactArtifactBytes:true,crossReleaseEdges:false,signatureCoverage:true,rollbackLineage:true}};graph.identity=H(Buffer.from(C(graph)));const gb=Buffer.from(C(graph)+'\n');const gd=H(gb);await writeFile(path.join(oci,'blobs','sha256',gd),gb);const manifest={schemaVersion:2,mediaType:'application/vnd.oci.image.manifest.v1+json',config:{mediaType:'application/vnd.fia.release-artifact-graph.v1+json',digest:`sha256:${gd}`,size:gb.length},layers};const mb=Buffer.from(C(manifest)+'\n');const md=H(mb);await writeFile(path.join(oci,'blobs','sha256',md),mb);const index={schemaVersion:2,manifests:[{mediaType:manifest.mediaType,digest:`sha256:${md}`,size:mb.length,annotations:{'org.opencontainers.image.ref.name':rel,'fia.graph.identity':graph.identity}}]};await writeFile(path.join(oci,'index.json'),C(index)+'\n');await writeFile(path.join(oci,'oci-layout'),C({imageLayoutVersion:'1.0.0'})+'\n');if(mutator)await mutator({d,oci,index,manifest,graph,md,gd,nodes});return d;
}
function run(d){return spawnSync(process.execPath,[exe,'--layoutDir',path.join(d,'oci'),'--restoreDir',path.join(d,'restore'),'--output',path.join(d,'out.json')],{encoding:'utf8'});}
test('restores deterministic graph closure',async()=>{const a=await fixture(),b=await fixture();assert.equal(run(a).status,0);assert.equal(run(b).status,0);const x=JSON.parse(await readFile(path.join(a,'out.json'))),y=JSON.parse(await readFile(path.join(b,'out.json')));assert.equal(x.identity,y.identity);assert.equal(x.graphIdentity,y.graphIdentity)});
test('rejects missing blob',async()=>{const d=await fixture(async({oci,nodes})=>{await import('node:fs/promises').then(fs=>fs.rm(path.join(oci,'blobs','sha256',nodes[1].artifactSha256)))});assert.notEqual(run(d).status,0)});
test('rejects descriptor substitution',async()=>{const d=await fixture(async({oci,index})=>{index.manifests[0].size++;await writeFile(path.join(oci,'index.json'),C(index)+'\n')});assert.notEqual(run(d).status,0)});
test('rejects hidden unreferenced blob',async()=>{const d=await fixture(async({oci})=>{await writeFile(path.join(oci,'blobs','sha256',H('hidden')),'hidden')});assert.notEqual(run(d).status,0)});
test('rejects cross-release evidence',async()=>{const d=await fixture(async({oci,nodes})=>{const p=path.join(oci,'blobs','sha256',nodes[2].artifactSha256);const obj=JSON.parse(await readFile(p));obj.releaseIdentity=H('other');await writeFile(p,C(obj)+'\n')});assert.notEqual(run(d).status,0)});
test('rejects graph without rollback lineage',async()=>{const d=await fixture(async({oci,graph,gd})=>{graph.edges=graph.edges.filter(e=>e.type!=='rolls-back-to');delete graph.identity;graph.identity=H(Buffer.from(C(graph)));const b=Buffer.from(C(graph)+'\n');await writeFile(path.join(oci,'blobs','sha256',gd),b)});assert.notEqual(run(d).status,0)});
test('preserves existing outputs',async()=>{const d=await fixture();await mkdir(path.join(d,'restore'));await writeFile(path.join(d,'out.json'),'keep');assert.notEqual(run(d).status,0);assert.equal(await readFile(path.join(d,'out.json'),'utf8'),'keep')});
