import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, writeFile, readFile, lstat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { verifyOfflineDependencyReproducibility } from './verify-offline-dependency-reproducibility.mjs';

const sha256=value=>`sha256:${createHash('sha256').update(value).digest('hex')}`;
function sort(value){if(Array.isArray(value))return value.map(sort);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,sort(value[k])]));return value;}
const canonical=value=>JSON.stringify(sort(value));
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'fia-deps-repro-test-')),cacheDir=path.join(root,'cache'),cacheManifest=path.join(root,'cache-manifest.json'),attestation=path.join(root,'repro.json');await mkdir(cacheDir);const lock={lockfileVersion:3,packages:{}};await writeFile(path.join(root,'package-lock.json'),JSON.stringify(lock));const core={schema:'fia.owned-npm-cache-manifest.v1',lockfile:sha256(Buffer.from(JSON.stringify(lock))),packages:[],status:'compiled-and-verified'};const manifest={...core,manifest:sha256(Buffer.from(canonical(core)))};await writeFile(cacheManifest,canonical(manifest));return{root,cacheDir,cacheManifest,attestation};}
function installer({variant=()=> 'stable'}={}){let call=0;return async({workspace,attestation})=>{call++;const modules=path.join(workspace,'node_modules','fixture');await mkdir(modules,{recursive:true});await writeFile(path.join(modules,'index.js'),variant(call));const bytes=await readFile(path.join(modules,'index.js'));const inventory=[{path:'fixture/index.js',bytes:bytes.length,sha256:sha256(bytes),mode:(await lstat(path.join(modules,'index.js'))).mode&0o777}];const core={schema:'fia.owned-npm-dependency-installation.v1',lockfile:'sha256:'+'1'.repeat(64),cacheManifest:'sha256:'+'2'.repeat(64),cacheManifestFile:'sha256:'+'3'.repeat(64),packages:[],npmCommand:'npm',installArguments:['ci','--offline','--ignore-scripts','--audit=false','--fund=false'],stdout:sha256(Buffer.alloc(0)),stderr:sha256(Buffer.alloc(0)),inventory,status:'installed-offline'};const record={...core,attestation:sha256(Buffer.from(canonical(core)))};await writeFile(attestation,canonical(record));return record;};}
test('two independent offline installs produce stable evidence',async()=>{const a=await fixture(),b=await fixture();const ra=await verifyOfflineDependencyReproducibility({...a,source:a.root,installer:installer()}),rb=await verifyOfflineDependencyReproducibility({...b,source:b.root,installer:installer()});assert.equal(ra.attestation,rb.attestation);assert.equal(ra.inventoryIdentity,rb.inventoryIdentity);});
test('rejects divergent installed dependency bytes',async()=>{const f=await fixture();await assert.rejects(()=>verifyOfflineDependencyReproducibility({...f,source:f.root,installer:installer({variant:n=>`value-${n}`})}),/mismatch at attempt 2/);});
test('rejects forged installation attestation',async()=>{const f=await fixture();const bad=async args=>{const r=await installer()(args);return{...r,attestation:'sha256:'+'0'.repeat(64)};};await assert.rejects(()=>verifyOfflineDependencyReproducibility({...f,source:f.root,installer:bad}),/identity mismatch/);});
test('rejects symlinks in installed tree',async()=>{const f=await fixture();const bad=async({workspace})=>{const fs=await import('node:fs/promises');const dir=path.join(workspace,'node_modules','fixture');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'target'),'x');await fs.symlink('target',path.join(dir,'link'));const core={schema:'fia.owned-npm-dependency-installation.v1',inventory:[],status:'installed-offline'};return{...core,attestation:sha256(Buffer.from(canonical(core)))};};await assert.rejects(()=>verifyOfflineDependencyReproducibility({...f,source:f.root,installer:bad}),/symbolic link rejected/);});
test('validates attempt count before installation',async()=>{const f=await fixture();await assert.rejects(()=>verifyOfflineDependencyReproducibility({...f,source:f.root,attempts:1,installer:installer()}),/attempts must/);});
test('refuses to overwrite retained attestation',async()=>{const f=await fixture();await writeFile(f.attestation,'retained');await assert.rejects(()=>verifyOfflineDependencyReproducibility({...f,source:f.root,installer:installer()}),/EEXIST/);assert.equal(await readFile(f.attestation,'utf8'),'retained');});
