import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
const exe=new URL('./gc-owned-artifact-registry.mjs',import.meta.url).pathname;
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const digest=b=>'sha256:'+crypto.createHash('sha256').update(b).digest('hex');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'fia-gc-')),registry=path.join(root,'registry');fs.mkdirSync(path.join(registry,'blobs','sha256'),{recursive:true});const blobs={};function add(s){const b=Buffer.from(s),d=digest(b);fs.writeFileSync(path.join(registry,'blobs','sha256',d.slice(7)),b);blobs[d]={size:b.length,mediaType:'application/octet-stream'};return d}const shared=add('shared'),current=add('current'),rollback=add('rollback'),orphan=add('orphan');const rid1=digest(Buffer.from('release-current')),rid0=digest(Buffer.from('release-rollback')),ridX=digest(Buffer.from('release-old'));const rel=(id,objs)=>({releaseIdentity:id,catalogDigest:objs[0],catalogSha256:objs[0],roots:[objs[0]],objectDigests:objs});const index={schema:'foundation.artifact.registry.index.v1',generation:7,releases:{[rid1]:rel(rid1,[current,shared]),[rid0]:rel(rid0,[rollback,shared]),[ridX]:rel(ridX,[orphan])},blobs};fs.mkdirSync(path.join(registry,'locks'),{recursive:true});fs.writeFileSync(path.join(registry,'index.json'),canonical(index)+'\n');const request={schema:'foundation.artifact.registry.gc.request.v1',retainReleaseIdentities:[rid1,rid0],rollbackEdges:[{from:rid1,to:rid0}]};const requestFile=path.join(root,'request.json'),output=path.join(root,'evidence.json');fs.writeFileSync(requestFile,canonical(request)+'\n');return {root,registry,requestFile,output,rid1,rid0,ridX,shared,current,rollback,orphan}}
function run(f,env={}){return spawnSync(process.execPath,[exe,'--registry',f.registry,'--request',f.requestFile,'--output',f.output],{encoding:'utf8',env:{...process.env,...env}})}
test('collects unreachable blobs while retaining rollback ancestry',()=>{const f=fixture(),r=run(f);assert.equal(r.status,0,r.stderr);const idx=JSON.parse(fs.readFileSync(path.join(f.registry,'index.json')));assert.deepEqual(Object.keys(idx.releases).sort(),[f.rid0,f.rid1].sort());assert.equal(fs.existsSync(path.join(f.registry,'blobs','sha256',f.orphan.slice(7))),false);assert.equal(fs.existsSync(path.join(f.registry,'blobs','sha256',f.shared.slice(7))),true);const ev=JSON.parse(fs.readFileSync(f.output));assert.equal(ev.checks.rollbackTargetsRetained,true)});
test('equivalent registries produce identical evidence identities',()=>{const a=fixture(),b=fixture();assert.equal(run(a).status,0);assert.equal(run(b).status,0);assert.equal(JSON.parse(fs.readFileSync(a.output)).identity,JSON.parse(fs.readFileSync(b.output)).identity)});
test('corrupted retained blob is rejected before quarantine',()=>{const f=fixture();fs.writeFileSync(path.join(f.registry,'blobs','sha256',f.current.slice(7)),'bad');const before=fs.readFileSync(path.join(f.registry,'index.json'));const r=run(f);assert.notEqual(r.status,0);assert.deepEqual(fs.readFileSync(path.join(f.registry,'index.json')),before);assert.equal(fs.existsSync(f.output),false)});
test('rollback target omission is rejected',()=>{const f=fixture();const q=JSON.parse(fs.readFileSync(f.requestFile));q.retainReleaseIdentities=[f.rid1];fs.writeFileSync(f.requestFile,canonical(q)+'\n');const r=run(f);assert.notEqual(r.status,0);assert.match(r.stderr,/rollback target not retained/);assert.equal(fs.existsSync(path.join(f.registry,'blobs','sha256',f.orphan.slice(7))),true)});
test('maintenance lock prevents mutation',()=>{const f=fixture();fs.writeFileSync(path.join(f.registry,'locks','maintenance.lock'),'held');const before=fs.readFileSync(path.join(f.registry,'index.json'));const r=run(f);assert.notEqual(r.status,0);assert.deepEqual(fs.readFileSync(path.join(f.registry,'index.json')),before)});
test('failure after quarantine restores all blobs and index',()=>{const f=fixture(),before=fs.readFileSync(path.join(f.registry,'index.json'));const r=run(f,{FIA_TEST_FAIL_AFTER_QUARANTINE:'1'});assert.notEqual(r.status,0);assert.deepEqual(fs.readFileSync(path.join(f.registry,'index.json')),before);for(const d of [f.shared,f.current,f.rollback,f.orphan])assert.equal(fs.existsSync(path.join(f.registry,'blobs','sha256',d.slice(7))),true)});
test('failure after index publication rolls back index and quarantine',()=>{const f=fixture(),before=fs.readFileSync(path.join(f.registry,'index.json'));const r=run(f,{FIA_TEST_FAIL_AFTER_INDEX:'1'});assert.notEqual(r.status,0);assert.deepEqual(fs.readFileSync(path.join(f.registry,'index.json')),before);for(const d of [f.shared,f.current,f.rollback,f.orphan])assert.equal(fs.existsSync(path.join(f.registry,'blobs','sha256',d.slice(7))),true);assert.equal(fs.existsSync(f.output),false)});
test('existing evidence prevents registry mutation',()=>{const f=fixture();fs.writeFileSync(f.output,'keep');const before=fs.readFileSync(path.join(f.registry,'index.json'));const r=run(f);assert.notEqual(r.status,0);assert.equal(fs.readFileSync(f.output,'utf8'),'keep');assert.deepEqual(fs.readFileSync(path.join(f.registry,'index.json')),before)});
