import test from 'node:test';import assert from 'node:assert/strict';import{createHash}from'node:crypto';import{access,mkdtemp,mkdir,readFile,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{collect}from'./gc-owned-artifact-registry-v2.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');const canon=v=>`${JSON.stringify(v)}\n`;async function ex(p){try{await access(p);return true}catch{return false}}
async function fx(){const root=await mkdtemp(join(tmpdir(),'fia-gcv2-')),registry=join(root,'registry');await mkdir(join(registry,'blobs','sha256'),{recursive:true});const a=Buffer.from('shared'),b=Buffer.from('dead');const da=`sha256:${sha(a)}`,db=`sha256:${sha(b)}`;await writeFile(join(registry,'blobs','sha256',sha(a)),a);await writeFile(join(registry,'blobs','sha256',sha(b)),b);const r1=`sha256:${'1'.repeat(64)}`,r2=`sha256:${'2'.repeat(64)}`;const index={schema:'foundation.artifact.registry.index.v1',generation:1,releases:{[r1]:{objects:[da]},[r2]:{objects:[db]}},objects:{[da]:{size:a.length},[db]:{size:b.length}}};await writeFile(join(registry,'index.json'),canon(index));const request=join(root,'request.json'),output=join(root,'out.json');await writeFile(request,canon({schema:'foundation.artifact.registry.gc.request.v1',retainReleaseIdentities:[r1],rollbackEdges:[]}));return{root,registry,request,output,da,db}}
test('collects unreachable blob and publishes v2 evidence',async()=>{const f=await fx();const e=await collect(f);assert.equal(e.schema,'foundation.artifact.registry.gc.v2');assert.equal(await ex(join(f.registry,'blobs','sha256',f.db.slice(7))),false);assert.equal((JSON.parse(await readFile(join(f.registry,'index.json')))).generation,2)});
test('writes durable prepared journal before mutation',async()=>{const f=await fx();await assert.rejects(collect({...f,failAt:'after-prepared'}));const tx=(await import('node:fs/promises')).readdir(join(f.registry,'transactions')).then(x=>x[0]);const j=JSON.parse(await readFile(join(f.registry,'transactions',await tx,'journal.json')));assert.equal(j.phase,'prepared');assert.equal(await ex(join(f.registry,'blobs','sha256',f.db.slice(7))),true)});
test('intent precedes move',async()=>{const f=await fx();await assert.rejects(collect({...f,failAt:`after-intent:${f.db}`}));const names=await (await import('node:fs/promises')).readdir(join(f.registry,'transactions'));const j=JSON.parse(await readFile(join(f.registry,'transactions',names[0],'journal.json')));assert.deepEqual(j.moveIntents,[f.db]);assert.deepEqual(j.movedDigests,[]);assert.equal(await ex(join(f.registry,'blobs','sha256',f.db.slice(7))),true)});
test('crash after move leaves reconcilable lag',async()=>{const f=await fx();await assert.rejects(collect({...f,failAt:`after-move:${f.db}`}));const names=await (await import('node:fs/promises')).readdir(join(f.registry,'transactions'));const j=JSON.parse(await readFile(join(f.registry,'transactions',names[0],'journal.json')));assert.deepEqual(j.moveIntents,[f.db]);assert.deepEqual(j.movedDigests,[]);assert.equal(await ex(join(f.registry,'blobs','sha256',f.db.slice(7))),false);assert.equal(await ex(join(f.registry,'quarantine',names[0],f.db.slice(7))),true)});
test('index publication precedes phase transition',async()=>{const f=await fx();await assert.rejects(collect({...f,failAt:'after-index'}));const names=await (await import('node:fs/promises')).readdir(join(f.registry,'transactions'));const j=JSON.parse(await readFile(join(f.registry,'transactions',names[0],'journal.json')));assert.equal(j.phase,'quarantining');assert.equal((JSON.parse(await readFile(join(f.registry,'index.json')))).generation,2)});
test('existing output prevents mutation',async()=>{const f=await fx();await writeFile(f.output,'keep');await assert.rejects(collect(f),/output already exists/);assert.equal(await readFile(f.output,'utf8'),'keep');assert.equal(await ex(join(f.registry,'blobs','sha256',f.db.slice(7))),true)});
test('rollback target must be retained',async()=>{const f=await fx();const r2=`sha256:${'2'.repeat(64)}`,r1=`sha256:${'1'.repeat(64)}`;await writeFile(f.request,canon({schema:'foundation.artifact.registry.gc.request.v1',retainReleaseIdentities:[r1],rollbackEdges:[{from:r1,to:r2}]}));await assert.rejects(collect(f),/rollback target not retained/)});
