import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync, sign } from 'node:crypto';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { planStartupRecoveryV2 } from './plan-artifact-registry-startup-recovery-v2.mjs';
const sha256 = (b) => `sha256:${createHash('sha256').update(b).digest('hex')}`;
const sortValue = (v) => Array.isArray(v) ? v.map(sortValue) : v && typeof v === 'object' ? Object.fromEntries(Object.keys(v).sort().map(k => [k, sortValue(v[k])])) : v;
const canonical = (v) => `${JSON.stringify(sortValue(v))}\n`;
const index = (generation, marker) => ({ schema:'foundation.artifact.registry.index.v1', generation, releases:{[marker]:{objects:[]}}, objects:{} });
async function fixture({ tamperSignature=false, overlap=false, branch=false, disconnected=false, keyPair=null }={}) {
  const root = await mkdtemp(join(tmpdir(),'fia-plan-v2-')); const registry=join(root,'registry'); await mkdir(join(registry,'transactions'),{recursive:true}); await mkdir(join(registry,'quarantine'),{recursive:true});
  const indexes=[index(1,'a'),index(2,'b'),index(3,'c')]; const bytes=indexes.map(v=>Buffer.from(canonical(v))); const digests=bytes.map(sha256); await writeFile(join(registry,'index.json'),bytes[2]);
  const txs=[{id:'gc-a',s:0,t:1,c:'sha256:'+ '1'.repeat(64),sup:null},{id:'gc-b',s:1,t:2,c:overlap?'sha256:'+ '1'.repeat(64):'sha256:'+ '2'.repeat(64),sup:'gc-a'}];
  if(branch) txs.push({id:'gc-c',s:1,t:2,c:'sha256:'+ '3'.repeat(64),sup:'gc-a'});
  for(const tx of txs){const dir=join(registry,'transactions',tx.id);await mkdir(dir,{recursive:true});await mkdir(join(registry,'quarantine',tx.id),{recursive:true}); const journal={schema:'foundation.artifact.registry.gc-journal.v2',transactionId:tx.id,phase:'quarantining',sourceIndexSha256:digests[tx.s],targetIndexSha256:digests[tx.t],candidateDigests:[tx.c],moveIntents:[tx.c],movedDigests:[],createdAt:'1970-01-01T00:00:00.000Z'};await writeFile(join(dir,'journal.json'),canonical(journal));await writeFile(join(dir,'source-index.json'),bytes[tx.s]);await writeFile(join(dir,'target-index.json'),bytes[tx.t]);}
  const {publicKey,privateKey}=keyPair ?? generateKeyPairSync('ed25519'); const signed={schema:'foundation.artifact.registry.startup-recovery-authorization.v1',keyId:'test-key',algorithm:'Ed25519',transactions:txs.map(tx=>({transactionId:tx.id,sourceIndexSha256:digests[tx.s],targetIndexSha256:disconnected&&tx.id==='gc-b'?'sha256:'+ 'f'.repeat(64):digests[tx.t],supersedes:tx.sup}))}; let signature=sign(null,Buffer.from(canonical(signed)),privateKey).toString('base64'); if(tamperSignature) signature=signature.slice(0,-4)+'AAAA'; const auth={...signed,signature}; const authPath=join(root,'auth.json'); const keyPath=join(root,'key.pem'); await writeFile(authPath,canonical(auth)); await writeFile(keyPath,publicKey.export({type:'spki',format:'pem'})); return {root,registry,authPath,keyPath,output:join(root,'out.json')};
}
test('signed linear chain selects terminal post-commit boundary',async()=>{const f=await fixture();const e=await planStartupRecoveryV2({registry:f.registry,authorization:f.authPath,publicKey:f.keyPath,output:f.output});assert.equal(e.action,'recover-post-commit');assert.equal(e.selectedTransactionId,'gc-b');assert.deepEqual(e.archivedSupersededTransactionIds,['gc-a']);});
test('equivalent fixtures produce identical evidence',async()=>{const keyPair=generateKeyPairSync('ed25519');const a=await fixture({keyPair}),b=await fixture({keyPair});const ea=await planStartupRecoveryV2({registry:a.registry,authorization:a.authPath,publicKey:a.keyPath,output:a.output});const eb=await planStartupRecoveryV2({registry:b.registry,authorization:b.authPath,publicKey:b.keyPath,output:b.output});assert.equal(ea.identity,eb.identity);});
test('different authorization keys produce different evidence identities',async()=>{const a=await fixture(),b=await fixture();const ea=await planStartupRecoveryV2({registry:a.registry,authorization:a.authPath,publicKey:a.keyPath,output:a.output});const eb=await planStartupRecoveryV2({registry:b.registry,authorization:b.authPath,publicKey:b.keyPath,output:b.output});assert.notEqual(ea.identity,eb.identity);assert.notEqual(ea.publicKeySha256,eb.publicKeySha256);});
test('invalid signature is rejected',async()=>{const f=await fixture({tamperSignature:true});await assert.rejects(()=>planStartupRecoveryV2({registry:f.registry,authorization:f.authPath,publicKey:f.keyPath,output:f.output}),/signature invalid/);});
test('candidate overlap is rejected',async()=>{const f=await fixture({overlap:true});await assert.rejects(()=>planStartupRecoveryV2({registry:f.registry,authorization:f.authPath,publicKey:f.keyPath,output:f.output}),/candidate overlap/);});
test('branching supersession is rejected',async()=>{const f=await fixture({branch:true});await assert.rejects(()=>planStartupRecoveryV2({registry:f.registry,authorization:f.authPath,publicKey:f.keyPath,output:f.output}),/branching supersession/);});
test('authorization transition mismatch is rejected',async()=>{const f=await fixture({disconnected:true});await assert.rejects(()=>planStartupRecoveryV2({registry:f.registry,authorization:f.authPath,publicKey:f.keyPath,output:f.output}),/authorization transition mismatch/);});
test('existing evidence is preserved',async()=>{const f=await fixture();await writeFile(f.output,'retained');await assert.rejects(()=>planStartupRecoveryV2({registry:f.registry,authorization:f.authPath,publicKey:f.keyPath,output:f.output}),/already exists/);assert.equal(await readFile(f.output,'utf8'),'retained');});
