import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,readlink,access,rm,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {promoteSovereignRelease} from './promote-sovereign-release.mjs';
async function fx(){const root=await mkdtemp(join(tmpdir(),'fia-promote-')),runtime=join(root,'runtime'),candidate=join(root,'candidate'),caps=join(root,'caps');await mkdir(join(runtime,'releases','old'),{recursive:true});await mkdir(candidate,{recursive:true});await mkdir(caps);await writeFile(join(runtime,'releases','old','index.json'),'old\n');await symlink(join('releases','old'),join(runtime,'active'));await writeFile(join(candidate,'index.json'),'new\n');await writeFile(join(candidate,'blob'),'payload\n');const candidateCapsule=join(caps,'new.fia'),rollbackCapsule=join(caps,'old.fia');await writeFile(candidateCapsule,'candidate capsule\n');await writeFile(rollbackCapsule,'rollback capsule\n');return{root,runtimeRoot:runtime,candidateRegistry:candidate,candidateCapsule,rollbackCapsule,releaseId:'new',rollbackReleaseId:'old',expectedActiveTarget:join('releases','old'),output:join(root,'promotion.json')}}
const gone=async p=>{try{await access(p);return false}catch{return true}};
test('installs immutable release, switches pointer, and retains rollback capsule',async()=>{const f=await fx();const e=await promoteSovereignRelease({...f,probe:async({activePath})=>({ok:(await readFile(join(activePath,'index.json'),'utf8'))==='new\n'})});assert.equal(e.verification.rollbackCapsule,true);assert.equal(await readlink(join(f.runtimeRoot,'active')),join('releases','new'));assert.equal(await readFile(join(f.runtimeRoot,'capsules','old.fia'),'utf8'),'rollback capsule\n');await rm(f.root,{recursive:true})});
test('equivalent promotion inputs produce identical evidence identities',async()=>{const a=await fx(),b=await fx();const ea=await promoteSovereignRelease(a),eb=await promoteSovereignRelease(b);assert.equal(ea.identity,eb.identity);await rm(a.root,{recursive:true});await rm(b.root,{recursive:true})});
test('active pointer drift fails before mutation',async()=>{const f=await fx();f.expectedActiveTarget='releases/other';await assert.rejects(promoteSovereignRelease(f),/active pointer drift/);assert.equal(await gone(join(f.runtimeRoot,'releases','new')),true);await rm(f.root,{recursive:true})});
test('failure before switch leaves prior pointer and no candidate authority',async()=>{const f=await fx();await assert.rejects(promoteSovereignRelease({...f,failpoint:'before-switch'}),/before pointer switch/);assert.equal(await readlink(join(f.runtimeRoot,'active')),join('releases','old'));assert.equal(await gone(join(f.runtimeRoot,'releases','new')),true);assert.equal(await gone(f.output),true);await rm(f.root,{recursive:true})});
test('failure after switch restores prior pointer',async()=>{const f=await fx();await assert.rejects(promoteSovereignRelease({...f,failpoint:'after-switch'}),/after pointer switch/);assert.equal(await readlink(join(f.runtimeRoot,'active')),join('releases','old'));assert.equal(await gone(join(f.runtimeRoot,'releases','new')),true);await rm(f.root,{recursive:true})});
test('false runtime success is rejected and rolled back',async()=>{const f=await fx();await assert.rejects(promoteSovereignRelease({...f,probe:async()=>({ok:false})}),/runtime probe failed/);assert.equal(await readlink(join(f.runtimeRoot,'active')),join('releases','old'));assert.equal(await gone(f.output),true);await rm(f.root,{recursive:true})});
test('existing evidence prevents mutation',async()=>{const f=await fx();await writeFile(f.output,'retain');await assert.rejects(promoteSovereignRelease(f),/already exists/);assert.equal(await readFile(f.output,'utf8'),'retain');assert.equal(await readlink(join(f.runtimeRoot,'active')),join('releases','old'));await rm(f.root,{recursive:true})});
