import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {mkdtemp,mkdir,writeFile,symlink,readlink,access,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {recoverSovereignReleasePromotion} from './recover-sovereign-release-promotion.mjs';
const sort=v=>Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;const canonical=v=>Buffer.from(`${JSON.stringify(sort(v))}\n`);const digest=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;const ex=async p=>{try{await access(p);return true}catch{return false}};
async function fixture(switched=false){const root=await mkdtemp(join(tmpdir(),'fia-promote-recover-')),releases=join(root,'releases'),capsules=join(root,'capsules');await mkdir(join(releases,'old'),{recursive:true});await mkdir(join(releases,'new'),{recursive:true});await mkdir(capsules);await writeFile(join(releases,'old','index.json'),'old');await writeFile(join(releases,'new','index.json'),'new');await writeFile(join(capsules,'old.fia'),'rollback');await writeFile(join(capsules,'new.fia'),'candidate');await symlink(switched?'releases/new':'releases/old',join(root,'active'));const inv=[{path:'index.json',size:3,sha256:digest(Buffer.from('new'))}],core={schema:'foundation.artifact.registry.sovereign-release-promotion-journal.v1',phase:'prepared',releaseId:'new',rollbackReleaseId:'old',activeBefore:'releases/old',registryIdentity:digest(canonical(inv)),candidateCapsuleSha256:digest(Buffer.from('candidate')),rollbackCapsuleSha256:digest(Buffer.from('rollback'))};await writeFile(join(root,'promotion-journal.json'),canonical({...core,identity:digest(canonical(core))}));return root}
test('rolls back pre-switch installation',async()=>{const r=await fixture(false),out=join(r,'e.json');const e=await recoverSovereignReleasePromotion({runtimeRoot:r,output:out});assert.equal(e.action,'rolled-back-pre-switch');assert.equal(await readlink(join(r,'active')),'releases/old');assert.equal(await ex(join(r,'releases/new')),false);assert.equal(await ex(join(r,'capsules/new.fia')),false);await rm(r,{recursive:true})});
test('finalizes valid post-switch authority',async()=>{const r=await fixture(true),out=join(r,'e.json');const e=await recoverSovereignReleasePromotion({runtimeRoot:r,output:out,probe:async()=>({ok:true})});assert.equal(e.action,'finalized-post-switch');assert.equal(await readlink(join(r,'active')),'releases/new');assert.equal(await ex(join(r,'promotion-journal.json')),false);await rm(r,{recursive:true})});
test('rejects unknown pointer',async()=>{const r=await fixture(false);await rm(join(r,'active'));await symlink('releases/other',join(r,'active'));await assert.rejects(()=>recoverSovereignReleasePromotion({runtimeRoot:r,output:join(r,'e.json')}),/neither previous nor candidate/);await rm(r,{recursive:true})});
test('rejects changed rollback capsule',async()=>{const r=await fixture(false);await writeFile(join(r,'capsules/old.fia'),'changed');await assert.rejects(()=>recoverSovereignReleasePromotion({runtimeRoot:r,output:join(r,'e.json')}),/rollback capsule mismatch/);await rm(r,{recursive:true})});
test('rejects partial post-switch candidate',async()=>{const r=await fixture(true);await rm(join(r,'capsules/new.fia'));await assert.rejects(()=>recoverSovereignReleasePromotion({runtimeRoot:r,output:join(r,'e.json')}),/incomplete/);await rm(r,{recursive:true})});
test('runtime probe failure preserves journal and candidate',async()=>{const r=await fixture(true);await assert.rejects(()=>recoverSovereignReleasePromotion({runtimeRoot:r,output:join(r,'e.json'),probe:async()=>({ok:false})}),/runtime probe failed/);assert.equal(await ex(join(r,'promotion-journal.json')),true);assert.equal(await ex(join(r,'releases/new')),true);await rm(r,{recursive:true})});
