import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,mkdir,readlink,symlink,writeFile,access} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {recoverSovereignReleaseRollback} from './recover-sovereign-release-rollback.mjs';
const sort=v=>Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;
const canonical=v=>Buffer.from(`${JSON.stringify(sort(v))}\n`);
const digest=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
async function exists(p){try{await access(p);return true}catch{return false}}
async function fixture({switched=false,partial=false,changedCapsule=false}={}){const root=await mkdtemp(join(tmpdir(),'fia-rb-rec-'));const runtime=join(root,'runtime'),releases=join(runtime,'releases'),caps=join(runtime,'capsules');await mkdir(join(releases,'failed'),{recursive:true});await mkdir(caps,{recursive:true});await writeFile(join(releases,'failed','index.json'),'failed');const target='releases/rollback';const capsule=Buffer.from('capsule-good');const core={schema:'foundation.artifact.registry.sovereign-release-rollback-journal.v1',phase:'prepared',rollbackReleaseId:'rollback',activeBefore:'releases/failed',target,capsuleSha256:digest(capsule),publicKeySha256:digest(Buffer.from('pub')),expectedRegistryIdentity:'sha256:registry'};const journal={...core,identity:digest(canonical(core))};await writeFile(join(runtime,'rollback-journal.json'),canonical(journal));await mkdir(join(releases,'rollback'),{recursive:true});await writeFile(join(releases,'rollback','index.json'),'rollback');if(!partial)await writeFile(join(caps,'rollback.fia'),changedCapsule?'bad':capsule);await symlink(switched?target:'releases/failed',join(runtime,'active'));return{root,runtime,output:join(root,'evidence.json')}}
test('pre-switch rollback removes incomplete installed authority',async()=>{const f=await fixture();const e=await recoverSovereignReleaseRollback({runtimeRoot:f.runtime,output:f.output});assert.equal(e.action,'rolled-back-pre-switch');assert.equal(await readlink(join(f.runtime,'active')),'releases/failed');assert.equal(await exists(join(f.runtime,'releases','rollback')),false);assert.equal(await exists(join(f.runtime,'rollback-journal.json')),false)});
test('post-switch finalizes only after served-generation proof',async()=>{const f=await fixture({switched:true});const e=await recoverSovereignReleaseRollback({runtimeRoot:f.runtime,output:f.output,probe:async()=>({ok:true,releaseId:'rollback',registryIdentity:'sha256:registry'})});assert.equal(e.action,'finalized-post-switch');assert.equal(e.servedGeneration.verified,true);assert.equal(await readlink(join(f.runtime,'active')),'releases/rollback')});
test('stale runtime serving candidate bytes is rejected and journal retained',async()=>{const f=await fixture({switched:true});await assert.rejects(()=>recoverSovereignReleaseRollback({runtimeRoot:f.runtime,output:f.output,probe:async()=>({ok:true,releaseId:'failed',registryIdentity:'sha256:other'})}),/served release identity mismatch/);assert.equal(await exists(join(f.runtime,'rollback-journal.json')),true);assert.equal(await exists(f.output),false)});
test('partial post-switch authority is rejected',async()=>{const f=await fixture({switched:true,partial:true});await assert.rejects(()=>recoverSovereignReleaseRollback({runtimeRoot:f.runtime,output:f.output,probe:async()=>({ok:true})}),/partial post-switch/)});
test('changed installed capsule is rejected',async()=>{const f=await fixture({switched:true,changedCapsule:true});await assert.rejects(()=>recoverSovereignReleaseRollback({runtimeRoot:f.runtime,output:f.output,probe:async()=>({ok:true})}),/capsule mismatch/)});
test('unknown active pointer is rejected',async()=>{const f=await fixture();const {unlink}=await import('node:fs/promises');await unlink(join(f.runtime,'active'));await symlink('releases/other',join(f.runtime,'active'));await assert.rejects(()=>recoverSovereignReleaseRollback({runtimeRoot:f.runtime,output:f.output}),/unknown authority/)});
test('equivalent pre-switch states have equal content identities',async()=>{const a=await fixture(),b=await fixture();const x=await recoverSovereignReleaseRollback({runtimeRoot:a.runtime,output:a.output}),y=await recoverSovereignReleaseRollback({runtimeRoot:b.runtime,output:b.output});assert.equal(x.contentIdentity,y.contentIdentity);assert.notEqual(x.identity,y.identity)});
