import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,stat} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {recoverArchive} from './recover-startup-recovery-archive.mjs';
const canonical=v=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);const sha=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;const shaObj=v=>sha(Buffer.from(canonical(v)));
async function fixture({post=false,loc='quarantine'}={}){const root=await mkdtemp(path.join(os.tmpdir(),'fia-ar-'));const reg=path.join(root,'reg'),out=path.join(root,'out.json');for(const d of ['transactions','startup-recovery-archive/quarantine','startup-recovery-archive/transactions'])await mkdir(path.join(reg,d),{recursive:true});const id='gc-old';const dir=path.join(reg,loc==='active'?'transactions':loc==='archived'?'startup-recovery-archive/transactions':'startup-recovery-archive/quarantine',id);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'journal.json'),'old');const inv=[{path:'journal.json',size:3,sha256:sha(Buffer.from('old'))}],inventorySha256=shaObj(inv);const records=[{transactionId:id,inventorySha256}];const indexBody={schema:'foundation.artifact.registry.startup-recovery-archive-index.v1',records};const index={...indexBody,identity:shaObj(indexBody)};const iBytes=Buffer.from(`${canonical(index)}\n`);if(post)await writeFile(path.join(reg,'startup-recovery-archive/index.json'),iBytes);const journal={archiveIndexSha256:sha(iBytes),createdAt:'1970-01-01T00:00:00.000Z',moveIntents:[id],movedTransactionIds:loc==='quarantine'||loc==='archived'?[id]:[],phase:post?'index-published':'moving',records,schema:'foundation.artifact.registry.startup-recovery-archive-journal.v1',transactionId:'archive-1'};await writeFile(path.join(reg,'startup-recovery-archive/journal.json'),`${canonical(journal)}\n`);return{root,reg,out,id}}
test('restores quarantine before commit',async()=>{const f=await fixture();const e=await recoverArchive({registry:f.reg,output:f.out});assert.equal(e.action,'rolled-back-pre-commit');await stat(path.join(f.reg,'transactions',f.id));});
test('finalizes quarantine after commit',async()=>{const f=await fixture({post:true});const e=await recoverArchive({registry:f.reg,output:f.out});assert.equal(e.action,'finalized-post-commit');await stat(path.join(f.reg,'startup-recovery-archive/transactions',f.id));});
test('equivalent states share content identity',async()=>{const a=await fixture(),b=await fixture();const ea=await recoverArchive({registry:a.reg,output:a.out}),eb=await recoverArchive({registry:b.reg,output:b.out});assert.equal(ea.contentIdentity,eb.contentIdentity);assert.notEqual(ea.identity,eb.identity)});
test('rejects duplicate active and quarantine authority',async()=>{const f=await fixture();const a=path.join(f.reg,'transactions',f.id);await mkdir(a);await writeFile(path.join(a,'journal.json'),'old');await assert.rejects(()=>recoverArchive({registry:f.reg,output:f.out}),/present in 2 locations/)});
test('rejects missing authority',async()=>{const f=await fixture();const q=path.join(f.reg,'startup-recovery-archive/quarantine',f.id);const {rm}=await import('node:fs/promises');await rm(q,{recursive:true});await assert.rejects(()=>recoverArchive({registry:f.reg,output:f.out}),/present in 0 locations/)});
test('rejects post-commit index with wrong digest',async()=>{const f=await fixture({post:true});await writeFile(path.join(f.reg,'startup-recovery-archive/index.json'),'{}');await assert.rejects(()=>recoverArchive({registry:f.reg,output:f.out}),/digest mismatch/)});
test('existing evidence prevents mutation',async()=>{const f=await fixture();await writeFile(f.out,'keep');await assert.rejects(()=>recoverArchive({registry:f.reg,output:f.out}),/already exists/);assert.equal(await readFile(f.out,'utf8'),'keep')});
