import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readlink,symlink,access} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {generateKeyPairSync} from 'node:crypto';
import {createStreamArchive} from './sovereign-release-capsule-stream.mjs';
import {rollbackSovereignRelease} from './rollback-sovereign-release.mjs';
const ex=async p=>{try{await access(p);return true}catch{return false}};
async function fixture(){const root=await mkdtemp(join(tmpdir(),'fia-rb-')),runtime=join(root,'runtime'),caps=join(root,'capsule'),old=join(runtime,'releases','candidate');await mkdir(old,{recursive:true});await writeFile(join(old,'index.json'),'candidate');await symlink('releases/candidate',join(runtime,'active'));await mkdir(caps,{recursive:true});await writeFile(join(caps,'index.json'),'rollback-index');await writeFile(join(caps,'archive-index.json'),'archive');await mkdir(join(caps,'blobs','sha256'),{recursive:true});await writeFile(join(caps,'blobs','sha256','abc'),'payload');const {privateKey,publicKey}=generateKeyPairSync('ed25519');const priv=join(root,'priv.pem'),pub=join(root,'pub.pem'),archive=join(root,'rollback.fia'),extract=join(root,'verify'),ev=join(root,'archive.json');await writeFile(priv,privateKey.export({type:'pkcs8',format:'pem'}));await writeFile(pub,publicKey.export({type:'spki',format:'pem'}));await createStreamArchive({capsuleDir:caps,privateKey:priv,publicKey:pub,archive,extractDir:extract,output:ev});return{root,runtime,pub,archive,output:join(root,'rollback.json')}}
test('installs rollback authority and switches active pointer',async()=>{const f=await fixture();const e=await rollbackSovereignRelease({runtimeRoot:f.runtime,output:f.output,rollbackCapsule:f.archive,publicKey:f.pub,rollbackReleaseId:'rollback',expectedActiveTarget:'releases/candidate'});assert.equal(await readlink(join(f.runtime,'active')),'releases/rollback');assert.equal(e.verification.runtimeProbe,true);assert.equal(await ex(join(f.runtime,'capsules','rollback.fia')),true)});
test('active drift fails before mutation',async()=>{const f=await fixture();await assert.rejects(()=>rollbackSovereignRelease({runtimeRoot:f.runtime,output:f.output,rollbackCapsule:f.archive,publicKey:f.pub,rollbackReleaseId:'rollback',expectedActiveTarget:'releases/other'}),/drift/);assert.equal(await readlink(join(f.runtime,'active')),'releases/candidate')});
test('failure before switch preserves prior authority',async()=>{const f=await fixture();await assert.rejects(()=>rollbackSovereignRelease({runtimeRoot:f.runtime,output:f.output,rollbackCapsule:f.archive,publicKey:f.pub,rollbackReleaseId:'rollback',expectedActiveTarget:'releases/candidate',failpoint:'before-switch'}),/injected/);assert.equal(await readlink(join(f.runtime,'active')),'releases/candidate');assert.equal(await ex(join(f.runtime,'releases','rollback')),false);assert.equal(await ex(f.archive),true)});
test('failure after switch restores prior authority',async()=>{const f=await fixture();await assert.rejects(()=>rollbackSovereignRelease({runtimeRoot:f.runtime,output:f.output,rollbackCapsule:f.archive,publicKey:f.pub,rollbackReleaseId:'rollback',expectedActiveTarget:'releases/candidate',failpoint:'after-switch'}),/injected/);assert.equal(await readlink(join(f.runtime,'active')),'releases/candidate');assert.equal(await ex(join(f.runtime,'releases','rollback')),false);assert.equal(await ex(f.archive),true)});
test('runtime probe failure rolls pointer back',async()=>{const f=await fixture();await assert.rejects(()=>rollbackSovereignRelease({runtimeRoot:f.runtime,output:f.output,rollbackCapsule:f.archive,publicKey:f.pub,rollbackReleaseId:'rollback',expectedActiveTarget:'releases/candidate',probe:async()=>({ok:false})}),/probe/);assert.equal(await readlink(join(f.runtime,'active')),'releases/candidate')});
test('wrong public key rejects signed capsule',async()=>{const f=await fixture();const {publicKey}=generateKeyPairSync('ed25519'),wrong=join(f.root,'wrong.pem');await writeFile(wrong,publicKey.export({type:'spki',format:'pem'}));await assert.rejects(()=>rollbackSovereignRelease({runtimeRoot:f.runtime,output:f.output,rollbackCapsule:f.archive,publicKey:wrong,rollbackReleaseId:'rollback',expectedActiveTarget:'releases/candidate'}),/public key mismatch/)});
