import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync} from 'node:crypto';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createArchive} from './sovereign-release-capsule-archive.mjs';
async function fixture(name='x'){const root=await mkdtemp(join(tmpdir(),`fia-${name}-`)),caps=join(root,'capsule');await mkdir(join(caps,'blobs','sha256'),{recursive:true});await mkdir(join(caps,'lineage','gc-a'),{recursive:true});await writeFile(join(caps,'manifest.json'),'{}\n');await writeFile(join(caps,'index.json'),'{"schema":"foundation.artifact.registry.index.v1"}\n');await writeFile(join(caps,'archive-index.json'),'{}\n');await writeFile(join(caps,'blobs','sha256','abc'),'payload');await writeFile(join(caps,'lineage','gc-a','journal.json'),'{}\n');const {privateKey,publicKey}=generateKeyPairSync('ed25519');const priv=join(root,'priv.pem'),pub=join(root,'pub.pem');await writeFile(priv,privateKey.export({format:'pem',type:'pkcs8'}));await writeFile(pub,publicKey.export({format:'pem',type:'spki'}));return{root,caps,priv,pub,archive:join(root,'capsule.fia'),extractDir:join(root,'out'),output:join(root,'evidence.json')}}
async function run(f,extra={}){return createArchive({capsuleDir:f.caps,privateKey:f.priv,publicKey:f.pub,archive:f.archive,extractDir:f.extractDir,output:f.output,...extra})}
test('creates deterministic signed single-file archive and extracts exact authority',async()=>{const f=await fixture();try{const e=await run(f);assert.equal(e.verification.cleanExtraction,true);assert.deepEqual(await readFile(join(f.extractDir,'blobs','sha256','abc'),'utf8'),'payload')}finally{await rm(f.root,{recursive:true,force:true})}});
test('equivalent inputs under same key are byte-identical',async()=>{const f=await fixture();try{const f2={...f,archive:join(f.root,'two.fia'),extractDir:join(f.root,'two-out'),output:join(f.root,'two.json')};const a=await run(f),b=await run(f2);assert.equal(a.identity,b.identity);assert.deepEqual(await readFile(f.archive),await readFile(f2.archive))}finally{await rm(f.root,{recursive:true,force:true})}});
test('truncated payload is rejected',async()=>{const f=await fixture();try{await assert.rejects(run(f,{mutateArchive:async p=>{const b=await readFile(p);await writeFile(p,b.subarray(0,b.length-1))}}),/truncated|mismatched|digest/)}finally{await rm(f.root,{recursive:true,force:true})}});
test('trailing hidden bytes are rejected',async()=>{const f=await fixture();try{await assert.rejects(run(f,{mutateArchive:async p=>{const b=await readFile(p);await writeFile(p,Buffer.concat([b,Buffer.from('hidden')]))}}),/trailing or hidden/)}finally{await rm(f.root,{recursive:true,force:true})}});
test('case-folding path collisions are rejected before publication',async()=>{const f=await fixture();try{await writeFile(join(f.caps,'A'),'a');await writeFile(join(f.caps,'a'),'b');await assert.rejects(run(f),/case-folding collision/)}finally{await rm(f.root,{recursive:true,force:true})}});
test('payload limit prevents decompression-style resource abuse',async()=>{const f=await fixture();try{await assert.rejects(run(f,{maxBytes:2}),/exceeds configured limit/)}finally{await rm(f.root,{recursive:true,force:true})}});
test('existing destinations prevent mutation',async()=>{const f=await fixture();try{await writeFile(f.output,'keep');await assert.rejects(run(f),/already exists/);assert.equal(await readFile(f.output,'utf8'),'keep')}finally{await rm(f.root,{recursive:true,force:true})}});
