import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,access,rm,appendFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {generateKeyPairSync} from 'node:crypto';import {createStreamArchive} from './sovereign-release-capsule-stream.mjs';
async function fx(){const root=await mkdtemp(join(tmpdir(),'fia-stream-')),caps=join(root,'capsule'),keys=join(root,'keys');await mkdir(join(caps,'blobs','sha256'),{recursive:true});await mkdir(keys);await writeFile(join(caps,'index.json'),'index\n');await writeFile(join(caps,'blobs','sha256','a'),'alpha');const {privateKey,publicKey}=generateKeyPairSync('ed25519');const priv=join(keys,'priv.pem'),pub=join(keys,'pub.pem');await writeFile(priv,privateKey.export({type:'pkcs8',format:'pem'}));await writeFile(pub,publicKey.export({type:'spki',format:'pem'}));return{root,capsuleDir:caps,privateKey:priv,publicKey:pub,archive:join(root,'x.fia'),extractDir:join(root,'extract'),output:join(root,'evidence.json')}}
const gone=async p=>{try{await access(p);return false}catch{return true}};
test('streams, verifies, extracts, and publishes',async()=>{const f=await fx();const e=await createStreamArchive(f);assert.equal(e.verification.boundedMemory,true);assert.equal((await readFile(join(f.extractDir,'blobs','sha256','a'),'utf8')),'alpha');await rm(f.root,{recursive:true})});
test('equivalent inputs produce byte-identical archives',async()=>{const a=await fx(),b=await fx();await rm(b.privateKey);await rm(b.publicKey);await writeFile(b.privateKey,await readFile(a.privateKey));await writeFile(b.publicKey,await readFile(a.publicKey));await createStreamArchive(a);await createStreamArchive(b);assert.deepEqual(await readFile(a.archive),await readFile(b.archive));assert.deepEqual(await readFile(a.output),await readFile(b.output));await rm(a.root,{recursive:true});await rm(b.root,{recursive:true})});
test('source mutation between inventory and stream fails closed',async()=>{const f=await fx();await assert.rejects(createStreamArchive({...f,beforeStreamFile:async(path,src)=>{if(path==='index.json')await appendFile(src,'changed')}}),/source changed/);assert.equal(await gone(f.archive),true);assert.equal(await gone(f.extractDir),true);assert.equal(await gone(f.output),true);await rm(f.root,{recursive:true})});
test('injected interruption leaves no authoritative outputs',async()=>{const f=await fx();await assert.rejects(createStreamArchive({...f,failAfterBytes:1}),/injected stream interruption/);assert.equal(await gone(f.archive),true);assert.equal(await gone(f.extractDir),true);assert.equal(await gone(f.output),true);await rm(f.root,{recursive:true})});
test('payload limits fail before publication',async()=>{const f=await fx();await assert.rejects(createStreamArchive({...f,maxBytes:2}),/payload limit/);assert.equal(await gone(f.archive),true);await rm(f.root,{recursive:true})});
test('existing destinations prevent mutation',async()=>{const f=await fx();await writeFile(f.output,'retain');await assert.rejects(createStreamArchive(f),/already exists/);assert.equal(await readFile(f.output,'utf8'),'retain');await rm(f.root,{recursive:true})});
