import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash,generateKeyPairSync} from 'node:crypto';import {createCapsule} from './sovereign-release-capsule.mjs';
const sort=v=>Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v,canonical=v=>`${JSON.stringify(sort(v))}\n`,dig=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
async function fx(keys){const root=await mkdtemp(path.join(os.tmpdir(),'fia-cap-')),reg=path.join(root,'reg'),exp=path.join(root,'exp'),res=path.join(root,'res'),out=path.join(root,'out.json'),priv=path.join(root,'priv.pem'),pub=path.join(root,'pub.pem');await mkdir(path.join(reg,'blobs','sha256'),{recursive:true});await mkdir(path.join(reg,'startup-recovery-archive','transactions','gc-a'),{recursive:true});const blob=Buffer.from('release-bytes'),d=dig(blob);await writeFile(path.join(reg,'blobs','sha256',d.slice(7)),blob);const idx={schema:'foundation.artifact.registry.index.v1',generation:1,releases:{current:{objects:[d],rollbackReleaseIdentity:'previous'}},objects:{[d]:{size:blob.length,mediaType:'text/plain'}}};await writeFile(path.join(reg,'index.json'),canonical(idx));const j=Buffer.from('journal');await writeFile(path.join(reg,'startup-recovery-archive','transactions','gc-a','journal.json'),j);const files=[{path:'journal.json',size:j.length,sha256:dig(j)}],records=[{transactionId:'gc-a',inventorySha256:dig(Buffer.from(canonical(files)))}],core={schema:'foundation.artifact.registry.startup-recovery-archive-index.v1',records},ai={...core,identity:dig(Buffer.from(canonical(core)))};await writeFile(path.join(reg,'startup-recovery-archive','index.json'),canonical(ai));keys??=generateKeyPairSync('ed25519');await writeFile(priv,keys.privateKey.export({type:'pkcs8',format:'pem'}));await writeFile(pub,keys.publicKey.export({type:'spki',format:'pem'}));return{root,reg,exp,res,out,priv,pub,d,keys}}
test('creates signed capsule and clean-host restore',async()=>{const f=await fx();const e=await createCapsule({registry:f.reg,privateKey:f.priv,publicKey:f.pub,exportDir:f.exp,restoreDir:f.res,output:f.out});assert.equal(e.verification.signature,true);assert.equal(await readFile(path.join(f.res,'blobs','sha256',f.d.slice(7)),'utf8'),'release-bytes')});
test('equivalent authority under same key is reproducible',async()=>{const k=generateKeyPairSync('ed25519'),a=await fx(k),b=await fx(k);const x=await createCapsule({registry:a.reg,privateKey:a.priv,publicKey:a.pub,exportDir:a.exp,restoreDir:a.res,output:a.out}),y=await createCapsule({registry:b.reg,privateKey:b.priv,publicKey:b.pub,exportDir:b.exp,restoreDir:b.res,output:b.out});assert.equal(x.identity,y.identity)});
test('rejects CAS substitution',async()=>{const f=await fx();await writeFile(path.join(f.reg,'blobs','sha256',f.d.slice(7)),'changed');await assert.rejects(()=>createCapsule({registry:f.reg,privateKey:f.priv,publicKey:f.pub,exportDir:f.exp,restoreDir:f.res,output:f.out}),/digest mismatch/)});
test('rejects lineage substitution',async()=>{const f=await fx();await writeFile(path.join(f.reg,'startup-recovery-archive','transactions','gc-a','journal.json'),'changed');await assert.rejects(()=>createCapsule({registry:f.reg,privateKey:f.priv,publicKey:f.pub,exportDir:f.exp,restoreDir:f.res,output:f.out}),/inventory mismatch/)});
test('rejects hidden capsule material',async()=>{const f=await fx();await assert.rejects(()=>createCapsule({registry:f.reg,privateKey:f.priv,publicKey:f.pub,exportDir:f.exp,restoreDir:f.res,output:f.out,injectHidden:'hidden.txt'}),/hidden or missing/)});
test('existing evidence prevents mutation',async()=>{const f=await fx();await writeFile(f.out,'keep');await assert.rejects(()=>createCapsule({registry:f.reg,privateKey:f.priv,publicKey:f.pub,exportDir:f.exp,restoreDir:f.res,output:f.out}),/already exists/);assert.equal(await readFile(f.out,'utf8'),'keep')});
