import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,stat} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {transportLineage} from './transport-startup-recovery-lineage.mjs';
const sort=v=>Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v,canonical=v=>`${JSON.stringify(sort(v))}\n`,dig=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
async function fx(){const root=await mkdtemp(path.join(os.tmpdir(),'fia-lt-')),reg=path.join(root,'reg'),exp=path.join(root,'exp'),res=path.join(root,'res'),out=path.join(root,'out.json');await mkdir(path.join(reg,'startup-recovery-archive','transactions','gc-a'),{recursive:true});await mkdir(path.join(reg,'blobs','sha256'),{recursive:true});const idx={schema:'foundation.artifact.registry.index.v1',generation:1,releases:{},objects:{}};await writeFile(path.join(reg,'index.json'),canonical(idx));const content=Buffer.from('journal');await writeFile(path.join(reg,'startup-recovery-archive','transactions','gc-a','journal.json'),content);const inv=[{path:'journal.json',size:content.length,sha256:dig(content)}],records=[{transactionId:'gc-a',inventorySha256:dig(Buffer.from(canonical(inv)))}],core={schema:'foundation.artifact.registry.startup-recovery-archive-index.v1',records},ai={...core,identity:dig(Buffer.from(canonical(core)))};await writeFile(path.join(reg,'startup-recovery-archive','index.json'),canonical(ai));return{root,reg,exp,res,out}}
test('exports and restores exact lineage',async()=>{const f=await fx();const e=await transportLineage({registry:f.reg,exportDir:f.exp,restoreDir:f.res,output:f.out});assert.equal(e.verification.cleanHostRestore,true);await stat(path.join(f.res,'startup-recovery-archive','transactions','gc-a','journal.json'))});
test('equivalent state is reproducible',async()=>{const a=await fx(),b=await fx();const x=await transportLineage({registry:a.reg,exportDir:a.exp,restoreDir:a.res,output:a.out}),y=await transportLineage({registry:b.reg,exportDir:b.exp,restoreDir:b.res,output:b.out});assert.equal(x.identity,y.identity)});
test('rejects archive inventory substitution',async()=>{const f=await fx();await writeFile(path.join(f.reg,'startup-recovery-archive','transactions','gc-a','journal.json'),'changed');await assert.rejects(()=>transportLineage({registry:f.reg,exportDir:f.exp,restoreDir:f.res,output:f.out}),/inventory mismatch/)});
test('rejects hidden snapshot material',async()=>{const f=await fx();await assert.rejects(()=>transportLineage({registry:f.reg,exportDir:f.exp,restoreDir:f.res,output:f.out,injectHidden:'hidden.txt'}),/hidden or missing/)});
test('rejects missing archived transaction',async()=>{const f=await fx();const {rm}=await import('node:fs/promises');await rm(path.join(f.reg,'startup-recovery-archive','transactions','gc-a'),{recursive:true});await assert.rejects(()=>transportLineage({registry:f.reg,exportDir:f.exp,restoreDir:f.res,output:f.out}),/closure mismatch/)});
test('existing output prevents mutation',async()=>{const f=await fx();await writeFile(f.out,'keep');await assert.rejects(()=>transportLineage({registry:f.reg,exportDir:f.exp,restoreDir:f.res,output:f.out}),/already exists/);assert.equal(await readFile(f.out,'utf8'),'keep')});
