import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp,mkdir,writeFile,readFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { verifyStartupRecoveryTransport } from './verify-startup-recovery-transport.mjs';
const sort=v=>Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;const canonical=v=>`${JSON.stringify(sort(v))}\n`;const digest=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
async function fixture(){const root=await mkdtemp(join(tmpdir(),'fia-transport-'));const registry=join(root,'registry');await mkdir(join(registry,'blobs','sha256'),{recursive:true});const a=Buffer.from('alpha'),b=Buffer.from('beta'),da=digest(a),db=digest(b);await writeFile(join(registry,'blobs','sha256',da.slice(7)),a);await writeFile(join(registry,'blobs','sha256',db.slice(7)),b);const index={schema:'foundation.artifact.registry.index.v1',generation:4,releases:{current:{objects:[da,db]}},objects:{[da]:{size:a.length},[db]:{size:b.length}}};const ib=Buffer.from(canonical(index));await writeFile(join(registry,'index.json'),ib);const contentCore={schema:'foundation.artifact.registry.startup-recovery.v1',planIdentity:digest(Buffer.from('plan')),selectedTransactionId:'gc-x',selectedRecoveryContentIdentity:digest(Buffer.from('selected')),authorizationContentIdentity:digest(Buffer.from('auth')),publicKeySha256:digest(Buffer.from('key')),activeIndexBefore:digest(ib),activeIndexAfter:digest(ib),retainedDigests:[da,db].sort(),archivedSupersededTransactionIds:[],selectedRecoveryEvidenceSha256:digest(Buffer.from('ev')),policy:{version:1}};const contentIdentity=digest(Buffer.from(canonical(contentCore)));const operationalId='op-1';const recovery={...contentCore,contentIdentity,operationalId,identity:digest(Buffer.from(canonical({contentIdentity,operationalId})))};const recoveryPath=join(root,'recovery.json');await writeFile(recoveryPath,canonical(recovery));return{root,registry,recoveryPath,da,db};}
async function run(f,s=''){return verifyStartupRecoveryTransport({registry:f.registry,recovery:f.recoveryPath,exportDir:join(f.root,`export${s}`),restoreDir:join(f.root,`restore${s}`),output:join(f.root,`evidence${s}.json`)});}
test('exports and clean-host restores exact authority',async()=>{const f=await fixture();try{const e=await run(f);assert.equal(e.verification.cleanHostRestore,true);assert.deepEqual(e.retainedObjectDigests,[f.da,f.db].sort());assert.deepEqual(await readFile(join(f.root,'restore','index.json')),await readFile(join(f.registry,'index.json')))}finally{await rm(f.root,{recursive:true,force:true})}});
test('equivalent runs are reproducible',async()=>{const a=await fixture(),b=await fixture();try{assert.equal((await run(a)).identity,(await run(b)).identity)}finally{await rm(a.root,{recursive:true,force:true});await rm(b.root,{recursive:true,force:true})}});
test('corrupted registry blob is rejected',async()=>{const f=await fixture();try{await writeFile(join(f.registry,'blobs','sha256',f.da.slice(7)),'wrong');await assert.rejects(run(f),/blob mismatch/)}finally{await rm(f.root,{recursive:true,force:true})}});
test('registry index drift from recovery evidence is rejected',async()=>{const f=await fixture();try{const i=JSON.parse(await readFile(join(f.registry,'index.json')));i.generation=5;await writeFile(join(f.registry,'index.json'),canonical(i));await assert.rejects(run(f),/differs from recovery evidence/)}finally{await rm(f.root,{recursive:true,force:true})}});
test('hidden snapshot material is rejected during restore',async()=>{const f=await fixture();try{await assert.rejects(verifyStartupRecoveryTransport({registry:f.registry,recovery:f.recoveryPath,exportDir:join(f.root,'export-hidden'),restoreDir:join(f.root,'restore-hidden'),output:join(f.root,'evidence-hidden.json'),injectHiddenSnapshotPath:'hidden'}),/hidden or missing snapshot material/)}finally{await rm(f.root,{recursive:true,force:true})}});
test('existing outputs prevent mutation',async()=>{const f=await fixture();try{await mkdir(join(f.root,'export'));await assert.rejects(run(f),/already exists/)}finally{await rm(f.root,{recursive:true,force:true})}});
