import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { acquireCasAuthorityLock,publishUnderCasAuthority,recoverUnderCasAuthority } from './fia-cas-authority-transaction.mjs';
const hash=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
const tmp=()=>fs.mkdtemp(path.join(os.tmpdir(),'fia-cas-auth-'));
async function fixture(){const root=await tmp(),cas=path.join(root,'cas'),out=path.join(root,'out'),journal=path.join(root,'journal.json');await fs.mkdir(out,{recursive:true});await fs.writeFile(path.join(out,'a.txt'),'alpha');const j={schema:'foundation.build.self-hosted-worker-transaction-journal.v2',transactionId:'tx',sourceExecutionIdentity:'source',expectedManifestPath:'manifests/source.json',phase:'prepared',claimedObjectDigests:[],policy:{}};await fs.writeFile(journal,JSON.stringify(j));return {root,cas,out,journal}}
test('publisher persists claims before object publication and releases shared lock',async()=>{const f=await fixture();let observed=false;const r=await publishUnderCasAuthority({...f,casRoot:f.cas,outputDir:f.out,journalPath:f.journal,evidencePath:path.join(f.root,'pub.json'),sourceExecutionIdentity:'source',publish:async()=>{const j=JSON.parse(await fs.readFile(f.journal));assert.deepEqual(j.claimedObjectDigests,[hash(Buffer.from('alpha'))]);assert.equal(j.phase,'objects-claimed');assert.equal(await fs.stat(path.join(f.cas,'.authority.lock')).then(()=>true),true);observed=true;return {contentIdentity:'sha256:'+ '1'.repeat(64)}}});assert.equal(observed,true);assert.equal(await fs.access(path.join(f.cas,'.authority.lock')).then(()=>true,()=>false),false);assert.equal(r.operation,'publish')});
test('collector and publisher share one exclusive authority lock',async()=>{const f=await fixture();const g=await acquireCasAuthorityLock({casRoot:f.cas,operation:'test'});await assert.rejects(()=>publishUnderCasAuthority({...f,casRoot:f.cas,outputDir:f.out,journalPath:f.journal,evidencePath:path.join(f.root,'e'),sourceExecutionIdentity:'source',publish:async()=>({contentIdentity:'x'})}),/lock exists/);await assert.rejects(()=>recoverUnderCasAuthority({casRoot:f.cas,journalDir:path.join(f.root,'journals'),evidencePath:path.join(f.root,'r'),recover:async()=>({contentIdentity:'x'})}),/lock exists/);await g.release()});
test('failure after durable claims leaves claims and releases lock',async()=>{const f=await fixture();await assert.rejects(()=>publishUnderCasAuthority({...f,casRoot:f.cas,outputDir:f.out,journalPath:f.journal,evidencePath:path.join(f.root,'e'),sourceExecutionIdentity:'source',fault:'after-claims',publish:async()=>assert.fail()}),/after claims/);const j=JSON.parse(await fs.readFile(f.journal));assert.equal(j.claimedObjectDigests.length,1);assert.equal(await fs.access(path.join(f.cas,'.authority.lock')).then(()=>true,()=>false),false)});
test('lock ownership substitution is rejected',async()=>{const f=await fixture(),g=await acquireCasAuthorityLock({casRoot:f.cas,operation:'test'}),p=path.join(f.cas,'.authority.lock');const l=JSON.parse(await fs.readFile(p));l.operationalId='other';await fs.writeFile(p,JSON.stringify(l));await assert.rejects(()=>g.release(),/ownership changed/)});
test('equivalent publication authority has deterministic content identity',async()=>{const run=async()=>{const f=await fixture();return publishUnderCasAuthority({...f,casRoot:f.cas,outputDir:f.out,journalPath:f.journal,evidencePath:path.join(f.root,'e'),sourceExecutionIdentity:'source',publish:async()=>({contentIdentity:'sha256:'+ '2'.repeat(64)})})};const a=await run(),b=await run();assert.equal(a.contentIdentity,b.contentIdentity);assert.notEqual(a.operationalId,b.operationalId)});
test('reachability callback executes while shared lock is held',async()=>{const f=await fixture();let held=false;await recoverUnderCasAuthority({casRoot:f.cas,journalDir:path.join(f.root,'j'),evidencePath:path.join(f.root,'r'),recover:async()=>{held=await fs.access(path.join(f.cas,'.authority.lock')).then(()=>true,()=>false);return {contentIdentity:'sha256:'+ '3'.repeat(64)}}});assert.equal(held,true)});
