import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { createWorkerCasJournal, recoverWorkerCasTransaction } from './fia-self-hosted-worker-recovery.mjs';
import { publishWorkerOutputToCas } from './fia-worker-cas-publication.mjs';
const hash=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
const canon=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
async function inv(root){const out=[];async function walk(d){for(const e of (await fs.readdir(d,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){const p=path.join(d,e.name);if(e.isDirectory())await walk(p);else{const s=await fs.stat(p);out.push({path:path.relative(root,p).split(path.sep).join('/'),size:s.size,sha256:hash(await fs.readFile(p)),mode:s.mode&0o777})}}}await walk(root);return out}
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'fia-recovery-'));const output=path.join(root,'output'),cas=path.join(root,'cas'),ev=path.join(root,'evidence');await fs.mkdir(output,{recursive:true});await fs.writeFile(path.join(output,'index.html'),'<html lang="en"><title>x</title></html>');const outputIdentity=hash(Buffer.from(canon(await inv(output))));const worker={schema:'foundation.build.self-hosted-worker-execution.v3',contentIdentity:'sha256:'+'1'.repeat(64),outputIdentity};await fs.mkdir(ev,{recursive:true});await fs.writeFile(path.join(ev,'worker.json'),canon(worker)+'\n');const source='sha256:'+'a'.repeat(64);const manifestPath=`manifests/${source.replace(/[^A-Za-z0-9._-]/g,'_')}.json`;await createWorkerCasJournal({journalPath:path.join(ev,'journal.json'),sourceExecutionIdentity:source,manifestPath,workerOutputIdentity:worker.outputIdentity,workerContentIdentity:worker.contentIdentity});return {root,output,cas,ev,worker,source,manifestPath,paths:{journal:path.join(ev,'journal.json'),worker:path.join(ev,'worker.json'),casEvidence:path.join(ev,'cas.json'),v4:path.join(ev,'v4.json'),recovery:path.join(ev,'recovery.json')}}}
async function recover(f){return recoverWorkerCasTransaction({journalPath:f.paths.journal,outputDir:f.output,casRoot:f.cas,workerEvidencePath:f.paths.worker,casEvidencePath:f.paths.casEvidence,v4EvidencePath:f.paths.v4,recoveryEvidencePath:f.paths.recovery})}

test('resumes CAS publication from verified worker output',async()=>{const f=await fixture();const r=await recover(f);assert.equal(r.action,'resumed-cas-publication');assert.equal(await fs.stat(path.join(f.cas,f.manifestPath)).then(()=>true),true);await assert.rejects(fs.access(f.paths.journal));});
test('finalizes committed manifest when staging output is gone',async()=>{const f=await fixture();await publishWorkerOutputToCas({outputDir:f.output,casRoot:f.cas,evidencePath:f.paths.casEvidence,sourceExecutionIdentity:f.source,verifySource:async()=>({ok:true})});await fs.rm(f.output,{recursive:true});const r=await recover(f);assert.equal(r.action,'finalized-manifest-committed');assert.equal(JSON.parse(await fs.readFile(f.paths.v4,'utf8')).schema,'foundation.build.self-hosted-worker-execution.v4');});
test('equivalent recovery authority has deterministic content identity',async()=>{const a=await fixture(),b=await fixture();const ra=await recover(a),rb=await recover(b);assert.equal(ra.contentIdentity,rb.contentIdentity);assert.notEqual(ra.operationalId,rb.operationalId);});
test('missing staging before manifest commit fails closed',async()=>{const f=await fixture();await fs.rm(f.output,{recursive:true});await assert.rejects(recover(f),/output missing/);assert.equal(await fs.access(f.paths.journal).then(()=>true),true);});
test('mutated staging before manifest commit is rejected',async()=>{const f=await fixture();await fs.writeFile(path.join(f.output,'index.html'),'changed');await assert.rejects(recover(f),/mutated/);assert.equal(await fs.access(f.paths.journal).then(()=>true),true);});
test('exclusive recovery lock prevents competing recovery',async()=>{const f=await fixture();await fs.writeFile(`${f.paths.journal}.recovery.lock`,'held');await assert.rejects(recover(f),/EEXIST/);});
test('committed manifest with corrupted object is rejected',async()=>{const f=await fixture();await publishWorkerOutputToCas({outputDir:f.output,casRoot:f.cas,evidencePath:f.paths.casEvidence,sourceExecutionIdentity:f.source,verifySource:async()=>({ok:true})});const m=JSON.parse(await fs.readFile(path.join(f.cas,f.manifestPath),'utf8'));const p=path.join(f.cas,'objects','sha256',m.objects[0].digest.slice(7));await fs.writeFile(p,'corrupt');await assert.rejects(recover(f),/CAS (size|digest) mismatch/);assert.equal(await fs.access(f.paths.journal).then(()=>true),true);});