import test from 'node:test';import assert from 'node:assert/strict';import {promises as fs} from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {recoverCasReachability} from './fia-cas-reachability-recovery.mjs';
const H=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;const C=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
async function fixture({phase='moving'}={}){const r=await fs.mkdtemp(path.join(os.tmpdir(),'fia-reach-recover-')),cas=path.join(r,'cas'),obj=path.join(cas,'objects','sha256'),man=path.join(cas,'manifests'),journals=path.join(r,'journals'),q=path.join(cas,'quarantine','q'),qo=path.join(q,'objects');await fs.mkdir(obj,{recursive:true});await fs.mkdir(man,{recursive:true});await fs.mkdir(journals);await fs.mkdir(qo,{recursive:true});const liveB=Buffer.from('live'),orphanB=Buffer.from('orphan'),live={digest:H(liveB),size:liveB.length},orphan={digest:H(orphanB),size:orphanB.length};await fs.writeFile(path.join(obj,live.digest.slice(7)),liveB);await fs.writeFile(path.join(qo,orphan.digest.slice(7)),orphanB);const ma={schema:'foundation.build.worker-cas-manifest.v1',sourceExecutionIdentity:'src',sourceOutputIdentity:'out',files:[],objects:[live],policy:{}};await fs.writeFile(path.join(man,'live.json'),C({...ma,identity:H(Buffer.from(C(ma)))})+'\n');const pa={schema:'foundation.build.cas-reachability-plan.v1',manifests:[{name:'live.json',identity:H(Buffer.from(C(ma)))}],reachableDigests:[live.digest],claimedDigests:[],orphanObjects:[orphan],policy:{manifestClosureVerified:true,activeJournalClaimsReserved:true,hardLinksRejected:true,rollbackMapRetained:true,providerNeutral:true}},plan={...pa,identity:H(Buffer.from(C(pa)))};await fs.writeFile(path.join(q,'plan.json'),C(plan)+'\n');await fs.writeFile(path.join(q,'journal.json'),C({schema:'foundation.build.cas-reachability-journal.v1',planIdentity:plan.identity,phase,moved:[orphan.digest]})+'\n');return {r,cas,obj,man,journals,q,live,orphan}}
test('rolls back retained pre-commit moves',async()=>{const f=await fixture(),e=await recoverCasReachability({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e')});assert.equal(e.actions[0].action,'rolled-back-pre-commit');await fs.access(path.join(f.obj,f.orphan.digest.slice(7)));await assert.rejects(fs.access(f.q));});
test('verifies and retains committed quarantine',async()=>{const f=await fixture({phase:'committed'}),e=await recoverCasReachability({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e')});assert.equal(e.actions[0].action,'verified-committed');await fs.access(path.join(f.q,'objects',f.orphan.digest.slice(7)));});
test('equivalent authority yields identical content identity',async()=>{const a=await fixture(),b=await fixture(),x=await recoverCasReachability({casRoot:a.cas,journalDir:a.journals,evidencePath:path.join(a.r,'e')}),y=await recoverCasReachability({casRoot:b.cas,journalDir:b.journals,evidencePath:path.join(b.r,'e')});assert.equal(x.contentIdentity,y.contentIdentity);assert.notEqual(x.operationalId,y.operationalId)});
test('global lock rejects competing recovery',async()=>{const f=await fixture(),lock=path.join(f.cas,'.reachability.lock');await fs.writeFile(lock,'held');await assert.rejects(()=>recoverCasReachability({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e')}),/lock exists/);assert.equal(await fs.readFile(lock,'utf8'),'held')});
test('duplicate active and quarantined object fails closed',async()=>{const f=await fixture();await fs.copyFile(path.join(f.q,'objects',f.orphan.digest.slice(7)),path.join(f.obj,f.orphan.digest.slice(7)));await assert.rejects(()=>recoverCasReachability({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e')}),/duplicate active/);await fs.access(f.q)});
test('interrupted recovery releases the global lock',async()=>{const f=await fixture({phase:'committed'});await assert.rejects(()=>recoverCasReachability({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e'),fault:'after-first-transaction'}),/injected failure/);assert.equal(await fs.access(path.join(f.cas,'.reachability.lock')).then(()=>true).catch(()=>false),false)});
test('corrupted committed quarantine object is rejected',async()=>{const f=await fixture({phase:'committed'});await fs.writeFile(path.join(f.q,'objects',f.orphan.digest.slice(7)),'bad');await assert.rejects(()=>recoverCasReachability({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e')}),/mismatch/)});
