import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { publishWorkerOutputToCas } from './fia-worker-cas-publication.mjs';
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'fia-cas-'));const out=path.join(root,'out');await fs.mkdir(path.join(out,'assets'),{recursive:true});await fs.writeFile(path.join(out,'index.html'),'<html></html>');await fs.writeFile(path.join(out,'assets','app.js'),'console.log(1)');return{root,out,cas:path.join(root,'cas'),evidence:path.join(root,'evidence.json')}}
test('publishes verified output into CAS with manifest commit boundary',async()=>{const f=await fixture();const e=await publishWorkerOutputToCas({outputDir:f.out,casRoot:f.cas,evidencePath:f.evidence,sourceExecutionIdentity:'sha256:worker'});assert.equal(e.schema,'foundation.build.worker-cas-publication.v1');const manifests=await fs.readdir(path.join(f.cas,'manifests'));assert.equal(manifests.length,1);const objects=await fs.readdir(path.join(f.cas,'objects','sha256'));assert.equal(objects.length,2)});
test('equivalent outputs produce identical content identity',async()=>{const a=await fixture(),b=await fixture();const ea=await publishWorkerOutputToCas({outputDir:a.out,casRoot:a.cas,evidencePath:a.evidence,sourceExecutionIdentity:'sha256:worker'});const eb=await publishWorkerOutputToCas({outputDir:b.out,casRoot:b.cas,evidencePath:b.evidence,sourceExecutionIdentity:'sha256:worker'});assert.equal(ea.contentIdentity,eb.contentIdentity);assert.notEqual(ea.operationalId,eb.operationalId)});
test('source mutation during verification is rejected',async()=>{const f=await fixture();await assert.rejects(()=>publishWorkerOutputToCas({outputDir:f.out,casRoot:f.cas,evidencePath:f.evidence,sourceExecutionIdentity:'sha256:worker',verifySource:async()=>{await fs.writeFile(path.join(f.out,'index.html'),'changed');return{ok:true}}}),/mutated/);assert.equal(await fs.stat(f.evidence).then(()=>true,()=>false),false)});
test('existing CAS object corruption is rejected',async()=>{const f=await fixture();await publishWorkerOutputToCas({outputDir:f.out,casRoot:f.cas,evidencePath:f.evidence,sourceExecutionIdentity:'sha256:first'});const objs=await fs.readdir(path.join(f.cas,'objects','sha256'));await fs.writeFile(path.join(f.cas,'objects','sha256',objs[0]),'poison');await fs.rm(f.evidence);await assert.rejects(()=>publishWorkerOutputToCas({outputDir:f.out,casRoot:f.cas,evidencePath:f.evidence,sourceExecutionIdentity:'sha256:second'}),/CAS (size|digest) mismatch/)});
test('failure after object publication leaves no authoritative manifest',async()=>{const f=await fixture();await assert.rejects(()=>publishWorkerOutputToCas({outputDir:f.out,casRoot:f.cas,evidencePath:f.evidence,sourceExecutionIdentity:'sha256:worker',fault:'after-object-publish'}),/injected/);assert.equal(await fs.stat(path.join(f.cas,'manifests')).then(async()=> (await fs.readdir(path.join(f.cas,'manifests'))).length,()=>0),0);assert.equal(await fs.stat(f.evidence).then(()=>true,()=>false),false)});
test('symlinks and existing evidence fail closed',async()=>{const f=await fixture();await fs.symlink('/etc/passwd',path.join(f.out,'escape'));await assert.rejects(()=>publishWorkerOutputToCas({outputDir:f.out,casRoot:f.cas,evidencePath:f.evidence,sourceExecutionIdentity:'sha256:worker'}),/symbolic link/);await fs.rm(path.join(f.out,'escape'));await fs.writeFile(f.evidence,'sentinel');await assert.rejects(()=>publishWorkerOutputToCas({outputDir:f.out,casRoot:f.cas,evidencePath:f.evidence,sourceExecutionIdentity:'sha256:worker'}),/evidence exists/);assert.equal(await fs.readFile(f.evidence,'utf8'),'sentinel')});
