import test from 'node:test';import assert from 'node:assert/strict';import {promises as fs} from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {quarantineUnreachableCas} from './fia-cas-reachability-quarantine.mjs';
const H=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;const C=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
async function fixture(){const r=await fs.mkdtemp(path.join(os.tmpdir(),'fia-reach-')),cas=path.join(r,'cas'),obj=path.join(cas,'objects','sha256'),man=path.join(cas,'manifests'),journals=path.join(r,'journals');await fs.mkdir(obj,{recursive:true});await fs.mkdir(man,{recursive:true});await fs.mkdir(journals);const put=async s=>{const b=Buffer.from(s),d=H(b);await fs.writeFile(path.join(obj,d.slice(7)),b);return {digest:d,size:b.length}};const live=await put('live'),orphan=await put('orphan'),claimed=await put('claimed');const a={schema:'foundation.build.worker-cas-manifest.v1',sourceExecutionIdentity:'src',sourceOutputIdentity:'out',files:[],objects:[live],policy:{}};await fs.writeFile(path.join(man,'live.json'),C({...a,identity:H(Buffer.from(C(a)))})+'\n');await fs.writeFile(path.join(journals,'active.json'),JSON.stringify({claimedObjectDigests:[claimed.digest]}));return {r,cas,obj,journals,live,orphan,claimed}}
test('quarantines only unreachable unclaimed objects',async()=>{const f=await fixture(),e=await quarantineUnreachableCas({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e.json'),quarantineId:'q'});assert.deepEqual(e.quarantinedObjects,[f.orphan]);await fs.access(path.join(f.obj,f.live.digest.slice(7)));await fs.access(path.join(f.obj,f.claimed.digest.slice(7)));await fs.access(path.join(f.cas,'quarantine','q','objects',f.orphan.digest.slice(7)))});
test('equivalent authority yields identical content identity',async()=>{const a=await fixture(),b=await fixture();const x=await quarantineUnreachableCas({casRoot:a.cas,journalDir:a.journals,evidencePath:path.join(a.r,'e'),quarantineId:'q'}),y=await quarantineUnreachableCas({casRoot:b.cas,journalDir:b.journals,evidencePath:path.join(b.r,'e'),quarantineId:'q'});assert.equal(x.contentIdentity,y.contentIdentity)});
test('corrupt reachable object is rejected',async()=>{const f=await fixture();await fs.writeFile(path.join(f.obj,f.live.digest.slice(7)),'bad');await assert.rejects(()=>quarantineUnreachableCas({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e')}),/mismatch/)});
test('hard linked object is rejected',async()=>{const f=await fixture();await fs.link(path.join(f.obj,f.orphan.digest.slice(7)),path.join(f.r,'alias'));await assert.rejects(()=>quarantineUnreachableCas({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e')}),/hard-linked/)});
test('interruption rolls back all moves',async()=>{const f=await fixture();await assert.rejects(()=>quarantineUnreachableCas({casRoot:f.cas,journalDir:f.journals,evidencePath:path.join(f.r,'e'),quarantineId:'q',fault:'after-first-move'}),/injected/);await fs.access(path.join(f.obj,f.orphan.digest.slice(7)));await assert.rejects(fs.access(path.join(f.cas,'quarantine','q')))});
test('existing evidence prevents mutation',async()=>{const f=await fixture(),p=path.join(f.r,'e');await fs.writeFile(p,'sentinel');await assert.rejects(()=>quarantineUnreachableCas({casRoot:f.cas,journalDir:f.journals,evidencePath:p}),/evidence exists/);assert.equal(await fs.readFile(p,'utf8'),'sentinel')});
