import test from 'node:test';import assert from 'node:assert/strict';import {promises as fs} from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {proveHermeticReproducibility} from './fia-hermetic-proof.mjs';
const h=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
async function makeRun(root,name,{releaseByte='x',provider=false}={}){const r=path.join(root,name);await fs.mkdir(path.join(r,'materialized'),{recursive:true});await fs.mkdir(path.join(r,'installed','node_modules','demo'),{recursive:true});await fs.mkdir(path.join(r,'release'),{recursive:true});const mat={schema:'foundation.build.dependency-materialization.v1',identity:h('mat')};const inst={schema:'foundation.build.dependency-installation.v1',identity:h('inst'),materializationIdentity:mat.identity};const rel={schema:'foundation.build.release.v1',releaseIdentity:h(releaseByte)};await fs.writeFile(path.join(r,'materialized','materialization.json'),JSON.stringify(mat));await fs.writeFile(path.join(r,'installed','dependency-tree.json'),JSON.stringify(inst));await fs.writeFile(path.join(r,'installed','node_modules','demo','index.js'),'export default 1');await fs.writeFile(path.join(r,'release','manifest.json'),JSON.stringify(rel));await fs.writeFile(path.join(r,'release','index.html'),provider?'<html>vercel.app</html>':releaseByte);return r;}
test('equivalent independent runs produce one proof',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fia-proof-'));const a=await makeRun(root,'a'),b=await makeRun(root,'b');const e=await proveHermeticReproducibility({runA:a,runB:b,output:path.join(root,'proof.json'),sourceIdentity:'git:test'});assert.equal(e.materializationIdentity,h('mat'));assert.ok(e.contentIdentity.startsWith('sha256:'));});
test('dependency tree drift is rejected',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fia-proof-'));const a=await makeRun(root,'a'),b=await makeRun(root,'b');await fs.writeFile(path.join(b,'installed','node_modules','demo','index.js'),'changed');await assert.rejects(proveHermeticReproducibility({runA:a,runB:b,output:path.join(root,'p')}),/installedInventoryIdentity mismatch/);});
test('release byte drift is rejected',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fia-proof-'));const a=await makeRun(root,'a'),b=await makeRun(root,'b');await fs.writeFile(path.join(b,'release','index.html'),'changed');await assert.rejects(proveHermeticReproducibility({runA:a,runB:b,output:path.join(root,'p')}),/releaseInventoryIdentity mismatch/);});
test('provider coupling is rejected',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fia-proof-'));const a=await makeRun(root,'a',{provider:true}),b=await makeRun(root,'b',{provider:true});await assert.rejects(proveHermeticReproducibility({runA:a,runB:b,output:path.join(root,'p')}),/provider coupling/);});
test('symlinks and same roots fail closed',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fia-proof-'));const a=await makeRun(root,'a'),b=await makeRun(root,'b');await fs.symlink(path.join(a,'release','index.html'),path.join(a,'release','alias'));await assert.rejects(proveHermeticReproducibility({runA:a,runB:b,output:path.join(root,'p')}),/symlink/);await assert.rejects(proveHermeticReproducibility({runA:b,runB:b,output:path.join(root,'q')}),/distinct/);});
test('existing evidence remains immutable',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'fia-proof-'));const a=await makeRun(root,'a'),b=await makeRun(root,'b'),out=path.join(root,'p');await fs.writeFile(out,'keep');await assert.rejects(proveHermeticReproducibility({runA:a,runB:b,output:out}),/output exists/);assert.equal(await fs.readFile(out,'utf8'),'keep');});
