import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,mkdir,readFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {gzipSync} from 'node:zlib';import {createHash} from 'node:crypto';import {installDependencies} from './fia-dependency-install.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');const sri=b=>`sha512-${createHash('sha512').update(b).digest('base64')}`;
function field(s,n){const b=Buffer.alloc(n);b.write(s);return b}function tar(entries){const blocks=[];for(const e of entries){const h=Buffer.alloc(512);field(e.name,100).copy(h,0);field((e.mode??0o644).toString(8).padStart(7,'0')+'\0',8).copy(h,100);field('0000000\0',8).copy(h,108);field('0000000\0',8).copy(h,116);field(e.data.length.toString(8).padStart(11,'0')+'\0',12).copy(h,124);field('00000000000\0',12).copy(h,136);h.fill(32,148,156);h[156]=(e.type??'0').charCodeAt(0);field('ustar\0',6).copy(h,257);let sum=0;for(const x of h)sum+=x;field(sum.toString(8).padStart(6,'0')+'\0 ',8).copy(h,148);blocks.push(h,e.data,Buffer.alloc((512-e.data.length%512)%512))}blocks.push(Buffer.alloc(1024));return gzipSync(Buffer.concat(blocks))}
async function fixture(opts={}){const root=await mkdtemp(path.join(os.tmpdir(),'fia-install-'));const lockfile=path.join(root,'package-lock.json'),materialized=path.join(root,'mat'),output=path.join(root,'out');const pkg=Buffer.from(JSON.stringify({name:'demo',version:opts.version??'1.0.0',...(opts.pkg??{})}));const entries=opts.entries??[{name:'package/package.json',data:pkg},{name:'package/index.js',data:Buffer.from('export default 1\n')}];const blob=tar(entries);const integrity=sri(blob);const lock={lockfileVersion:3,packages:{'':{},'node_modules/demo':{version:'1.0.0',integrity}}};const lockBytes=Buffer.from(JSON.stringify(lock));await writeFile(lockfile,lockBytes);await mkdir(path.join(materialized,'objects','sha512'),{recursive:true});await writeFile(path.join(materialized,'objects','sha512','x.tgz'),blob);const mat={identity:'sha256:mat',lockfile:{sha256:`sha256:${sha(lockBytes)}`},packages:[{name:'demo',version:'1.0.0',integrity,cacheObject:'objects/sha512/x.tgz',sha256:`sha256:${sha(blob)}`,size:blob.length}]};await writeFile(path.join(materialized,'materialization.json'),JSON.stringify(mat));return {root,lockfile,materialized,output}}
test('installs deterministic verified tree and SBOM',async()=>{const a=await fixture(),b=await fixture();const ea=await installDependencies(a),eb=await installDependencies(b);assert.equal(ea.identity,eb.identity);assert.equal(await readFile(path.join(a.output,'node_modules/demo/index.js'),'utf8'),'export default 1\n');assert.ok(JSON.parse(await readFile(path.join(a.output,'sbom.json'))).packages.length===1)});
test('rejects traversal and symlink tar entries',async()=>{for(const entries of [[{name:'package/package.json',data:Buffer.from('{"name":"demo","version":"1.0.0"}')},{name:'package/../escape',data:Buffer.from('x')}],[{name:'package/package.json',data:Buffer.from('{"name":"demo","version":"1.0.0"}')},{name:'package/link',data:Buffer.alloc(0),type:'2'}]]){const f=await fixture({entries});await assert.rejects(()=>installDependencies(f),/unsafe archive path|unsupported tar entry type/)} });
test('rejects duplicate case-colliding paths',async()=>{const f=await fixture({entries:[{name:'package/package.json',data:Buffer.from('{"name":"demo","version":"1.0.0"}')},{name:'package/A.js',data:Buffer.from('a')},{name:'package/a.js',data:Buffer.from('b')}]});await assert.rejects(()=>installDependencies(f),/duplicate or case-colliding/)});
test('rejects package metadata mismatch',async()=>{const f=await fixture({version:'2.0.0'});await assert.rejects(()=>installDependencies(f),/package metadata mismatch/)});
test('rejects undeclared executable',async()=>{const f=await fixture({entries:[{name:'package/package.json',data:Buffer.from('{"name":"demo","version":"1.0.0"}')},{name:'package/postinstall.sh',data:Buffer.from('x'),mode:0o755}]});await assert.rejects(()=>installDependencies(f),/undeclared executable/)});
test('rejects poisoned materialized object and existing output',async()=>{const f=await fixture();await writeFile(path.join(f.materialized,'objects/sha512/x.tgz'),'bad');await assert.rejects(()=>installDependencies(f),/materialized object mismatch/);const g=await fixture();await mkdir(g.output);await writeFile(path.join(g.output,'sentinel'),'x');await assert.rejects(()=>installDependencies(g),/output exists/);assert.equal(await readFile(path.join(g.output,'sentinel'),'utf8'),'x')});
