#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';

const SCHEMA='foundation.build.release.v1';
const hash=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
const canon=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
const safeRel=p=>{const n=p.split(path.sep).join('/');if(!n||n.startsWith('/')||n.split('/').some(x=>!x||x==='.'||x==='..'))throw Error(`unsafe path: ${p}`);return n.normalize('NFC')};
async function walk(root,dir=root,out=[]){for(const e of (await fs.readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){const p=path.join(dir,e.name);if(e.isSymbolicLink())throw Error(`symbolic link rejected: ${p}`);if(e.isDirectory())await walk(root,p,out);else if(e.isFile())out.push({absolute:p,path:safeRel(path.relative(root,p))});else throw Error(`unsupported entry: ${p}`)}return out}
function routeFor(p){if(p==='index.html')return '/';if(p.endsWith('/index.html'))return '/'+p.slice(0,-11);if(p.endsWith('.html'))return '/'+p.slice(0,-5);return null}
function checkHtml(text,p){const errors=[];if(!/<html\b[^>]*\blang=/i.test(text))errors.push(`${p}: html lang missing`);if(!/<title>[^<]+<\/title>/i.test(text))errors.push(`${p}: title missing`);if(!/<meta\b[^>]*name=["']viewport["']/i.test(text))errors.push(`${p}: viewport missing`);for(const m of text.matchAll(/<img\b[^>]*>/gi))if(!/\balt\s*=/.test(m[0]))errors.push(`${p}: img alt missing`);for(const m of text.matchAll(/<(audio|video)\b[^>]*>/gi))if(/\bautoplay\b/i.test(m[0]))errors.push(`${p}: autoplay forbidden`);return errors}
async function atomicWrite(file,data){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.tmp-${process.pid}`;await fs.writeFile(tmp,data,{flag:'wx'});const h=await fs.open(tmp,'r');await h.sync();await h.close();await fs.rename(tmp,file)}
export async function build({input,output,sourceIdentity='unbound'}){input=path.resolve(input);output=path.resolve(output);try{await fs.access(output);throw Error(`output exists: ${output}`)}catch(e){if(e.code!=='ENOENT')throw e}const stage=`${output}.stage-${process.pid}`;await fs.mkdir(path.join(stage,'blobs','sha256'),{recursive:true});try{const files=await walk(input);if(!files.length)throw Error('input is empty');const seen=new Set(),entries=[],routes=[],a11y=[];for(const f of files){const fold=f.path.normalize('NFC').toLocaleLowerCase('en-US');if(seen.has(fold))throw Error(`case-fold collision: ${f.path}`);seen.add(fold);const bytes=await fs.readFile(f.absolute);const digest=hash(bytes);const hex=digest.slice(7);const blob=path.join(stage,'blobs','sha256',hex);try{await fs.copyFile(f.absolute,blob,fs.constants.COPYFILE_EXCL)}catch(e){if(e.code!=='EEXIST')throw e}entries.push({path:f.path,digest,size:bytes.length,mediaType:media(f.path)});const r=routeFor(f.path);if(r)routes.push({route:r,file:f.path,digest});if(f.path.endsWith('.html'))a11y.push(...checkHtml(bytes.toString('utf8'),f.path))}if(!routes.some(r=>r.route==='/'))throw Error('root route missing');if(a11y.length)throw Error(`accessibility gate failed:\n${a11y.join('\n')}`);entries.sort((a,b)=>a.path.localeCompare(b.path));routes.sort((a,b)=>a.route.localeCompare(b.route));const sbom={schema:'foundation.build.sbom.v1',components:entries.map(x=>({name:x.path,version:x.digest,type:'file'}))};const provenance={schema:'foundation.build.provenance.v1',builder:{id:'fia-build-v1'},sourceIdentity,parameters:{providerNeutral:true,offlineCapable:true},materials:[],subjects:entries.map(x=>({name:x.path,digest:x.digest}))};const authority={schema:SCHEMA,sourceIdentity,files:entries,routes,sbomDigest:hash(Buffer.from(canon(sbom))),provenanceDigest:hash(Buffer.from(canon(provenance))),policy:{accessibilityGate:true,noAutoplay:true,providerNeutral:true,contentAddressed:true}};const identity=hash(Buffer.from(canon(authority)));const manifest={...authority,identity};await atomicWrite(path.join(stage,'manifest.json'),canon(manifest)+'\n');await atomicWrite(path.join(stage,'routes.json'),canon({schema:'foundation.build.routes.v1',routes})+'\n');await atomicWrite(path.join(stage,'sbom.json'),canon(sbom)+'\n');await atomicWrite(path.join(stage,'provenance.json'),canon(provenance)+'\n');await atomicWrite(path.join(stage,'rollback.json'),canon({schema:'foundation.build.rollback.v1',releaseIdentity:identity,restore:{manifest:'manifest.json',blobs:'blobs/sha256'}})+'\n');await fs.rename(stage,output);return manifest}catch(e){await fs.rm(stage,{recursive:true,force:true});throw e}}
function media(p){const ext=path.extname(p).toLowerCase();return ({'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.woff2':'font/woff2'}[ext]||'application/octet-stream')}
function args(xs){const o={};for(let i=0;i<xs.length;i+=2){if(!xs[i]?.startsWith('--')||xs[i+1]===undefined)throw Error(`invalid argument: ${xs[i]}`);o[xs[i].slice(2)]=xs[i+1]}return o}
if(import.meta.url===`file://${process.argv[1]}`){const a=args(process.argv.slice(2));if(!a.input||!a.output){console.error('usage: fia-build.mjs --input <static-dir> --output <release-dir> [--sourceIdentity <id>]');process.exit(2)}build(a).then(m=>console.log(m.identity)).catch(e=>{console.error(e.message);process.exit(1)})}
