import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { compileSource } from './fia-source-build.mjs';

async function project(script) { const root=await fs.mkdtemp(path.join(os.tmpdir(),'fia-source-')); await fs.writeFile(path.join(root,'build.mjs'),script); return root; }
const good=`import {promises as fs} from 'node:fs'; await fs.mkdir('dist'); await fs.writeFile('dist/index.html','<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width"><title>MC</title></head><body>owned</body></html>');`;
test('two clean builds produce one reproducible release',async()=>{const src=await project(good);const out=path.join(src,'result');const result=await compileSource({source:src,output:out,command:[process.execPath,'build.mjs'],sourceIdentity:'git:test'});assert.equal(result.runs[0].releaseIdentity,result.runs[1].releaseIdentity);assert.equal(JSON.parse(await fs.readFile(path.join(out,'reproducibility.json'),'utf8')).contentIdentity,result.contentIdentity);});
test('ambient host environment is not inherited',async()=>{process.env.FIA_SECRET_LEAK='bad';const src=await project(`import {promises as fs} from 'node:fs'; await fs.mkdir('dist'); await fs.writeFile('dist/index.html','<!doctype html><html lang="en"><head><meta name="viewport" content="x"><title>x</title></head><body>'+String(process.env.FIA_SECRET_LEAK)+'</body></html>');`);const out=path.join(src,'result');await compileSource({source:src,output:out,command:[process.execPath,'build.mjs']});const manifest=JSON.parse(await fs.readFile(path.join(out,'release','manifest.json'),'utf8'));assert.ok(manifest.files.length);});
test('nondeterministic output is rejected',async()=>{const src=await project(`import {promises as fs} from 'node:fs'; await fs.mkdir('dist'); await fs.writeFile('dist/index.html','<!doctype html><html lang="en"><head><meta name="viewport" content="x"><title>x</title></head><body>'+Math.random()+'</body></html>');`);await assert.rejects(compileSource({source:src,output:path.join(src,'result'),command:[process.execPath,'build.mjs']}),/reproducibility mismatch/);});
test('provider-coupled output is rejected',async()=>{const src=await project(`import {promises as fs} from 'node:fs'; await fs.mkdir('dist'); await fs.writeFile('dist/index.html','<!doctype html><html lang="en"><head><meta name="viewport" content="x"><title>x</title></head><body>https://x.pages.dev</body></html>');`);await assert.rejects(compileSource({source:src,output:path.join(src,'result'),command:[process.execPath,'build.mjs']}),/provider coupling/);});
test('false success and existing output fail closed',async()=>{const src=await project(`process.exit(0)`);await assert.rejects(compileSource({source:src,output:path.join(src,'result'),command:[process.execPath,'build.mjs']}),/without declared output/);const src2=await project(good);const out=path.join(src2,'result');await fs.mkdir(out);await fs.writeFile(path.join(out,'sentinel'),'keep');await assert.rejects(compileSource({source:src2,output:out,command:[process.execPath,'build.mjs']}),/output exists/);assert.equal(await fs.readFile(path.join(out,'sentinel'),'utf8'),'keep');});
