import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createHash, generateKeyPairSync, sign } from 'node:crypto';
import { classifyLockOwner, recoverCasAuthority } from './fia-cas-authority-recovery.mjs';
const hash=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
const canon=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
const tmp=()=>fs.mkdtemp(path.join(os.tmpdir(),'fia-cas-recovery-'));
function lockAuthority(l){return {schema:l.schema,operation:l.operation,bootId:l.bootId,processStart:l.processStart,policy:l.policy}}
function authAuthority(a){return {schema:a.schema,action:a.action,lockContentIdentity:a.lockContentIdentity,lockOperationalId:a.lockOperationalId,publicKeySha256:a.publicKeySha256,recoveryPolicy:a.recoveryPolicy}}
async function fixture(keyPair){
 const root=await tmp(),cas=path.join(root,'cas'),lockPath=path.join(cas,'.authority.lock'),authPath=path.join(root,'authorization.json'),publicKeyPath=path.join(root,'public.pem'),evidencePath=path.join(root,'evidence.json');await fs.mkdir(cas,{recursive:true});
 const base={schema:'foundation.build.cas-authority-lock.v1',operation:'publish',bootId:'old-boot',processStart:'55',policy:{exclusive:true,sharedByPublishersAndCollectors:true,staleLocksFailClosed:true,providerNeutral:true}};const lock={...base,contentIdentity:hash(Buffer.from(canon(base))),operationalId:'old-operation',pid:4242};await fs.writeFile(lockPath,canon(lock)+'\n');
 const {privateKey,publicKey}=keyPair||generateKeyPairSync('ed25519');const publicBytes=publicKey.export({type:'spki',format:'pem'});await fs.writeFile(publicKeyPath,publicBytes);
 const aa={schema:'foundation.build.cas-authority-takeover-authorization.v1',action:'takeover-stale-cas-authority',lockContentIdentity:lock.contentIdentity,lockOperationalId:lock.operationalId,publicKeySha256:hash(publicBytes),recoveryPolicy:{reconcileInterruptedMutation:true,doNotDeleteUnexplainedAuthority:true}};const authorization={...aa,identity:hash(Buffer.from(canon(aa))),signature:sign(null,Buffer.from(canon(aa)),privateKey).toString('base64')};await fs.writeFile(authPath,canon(authorization)+'\n');
 return {root,cas,lockPath,authPath,publicKeyPath,evidencePath,lock,authorization};
}
test('classifies same-process owner as live and PID reuse as stale',async()=>{const f=await fixture();assert.deepEqual(await classifyLockOwner(f.lock,{currentBootId:'old-boot',processStartReader:async()=> '55'}),{status:'live',reason:'owner-matches'});assert.deepEqual(await classifyLockOwner(f.lock,{currentBootId:'old-boot',processStartReader:async()=> '99'}),{status:'stale',reason:'pid-reused'})});
test('signed takeover replaces stale lock only during reconciliation',async()=>{const f=await fixture();let observed=false;const r=await recoverCasAuthority({casRoot:f.cas,authorizationPath:f.authPath,publicKeyPath:f.publicKeyPath,evidencePath:f.evidencePath,currentBootId:'new-boot',reconcile:async({lockPath,newLock,oldLock})=>{const active=JSON.parse(await fs.readFile(lockPath));assert.equal(active.operationalId,newLock.operationalId);assert.equal(oldLock.operationalId,f.lock.operationalId);observed=true;return {contentIdentity:'sha256:'+ '1'.repeat(64)}}});assert.equal(observed,true);assert.equal(r.verification.authorizationSignatureVerified,true);assert.equal(await fs.access(f.lockPath).then(()=>true,()=>false),false);assert.equal(await fs.access(f.evidencePath).then(()=>true,()=>false),true)});
test('live owner is rejected before lock replacement',async()=>{const f=await fixture();await assert.rejects(()=>recoverCasAuthority({casRoot:f.cas,authorizationPath:f.authPath,publicKeyPath:f.publicKeyPath,evidencePath:f.evidencePath,currentBootId:'old-boot',processStartReader:async()=> '55',reconcile:async()=>assert.fail()}),/owner is live/);const retained=JSON.parse(await fs.readFile(f.lockPath));assert.equal(retained.operationalId,f.lock.operationalId)});
test('authorization signed by another key is rejected',async()=>{const f=await fixture();const {privateKey}=generateKeyPairSync('ed25519');const a=JSON.parse(await fs.readFile(f.authPath));const aa=authAuthority(a);a.signature=sign(null,Buffer.from(canon(aa)),privateKey).toString('base64');await fs.writeFile(f.authPath,canon(a));await assert.rejects(()=>recoverCasAuthority({casRoot:f.cas,authorizationPath:f.authPath,publicKeyPath:f.publicKeyPath,evidencePath:f.evidencePath,currentBootId:'new-boot'}),/signature verification failed/);assert.equal(JSON.parse(await fs.readFile(f.lockPath)).operationalId,f.lock.operationalId)});
test('failure after replacement restores exact predecessor lock',async()=>{const f=await fixture(),before=await fs.readFile(f.lockPath);await assert.rejects(()=>recoverCasAuthority({casRoot:f.cas,authorizationPath:f.authPath,publicKeyPath:f.publicKeyPath,evidencePath:f.evidencePath,currentBootId:'new-boot',fault:'after-lock-replacement'}),/injected failure/);assert.deepEqual(await fs.readFile(f.lockPath),before);assert.equal(await fs.access(f.evidencePath).then(()=>true,()=>false),false)});
test('concurrent takeover guard fails closed',async()=>{const f=await fixture();await fs.writeFile(path.join(f.cas,'.authority.takeover.lock'),'{}');await assert.rejects(()=>recoverCasAuthority({casRoot:f.cas,authorizationPath:f.authPath,publicKeyPath:f.publicKeyPath,evidencePath:f.evidencePath,currentBootId:'new-boot'}),/takeover already active/)});
test('equivalent authority yields deterministic content identity',async()=>{const keyPair=generateKeyPairSync('ed25519');const run=async()=>{const f=await fixture(keyPair);return recoverCasAuthority({casRoot:f.cas,authorizationPath:f.authPath,publicKeyPath:f.publicKeyPath,evidencePath:f.evidencePath,currentBootId:'new-boot',reconcile:async()=>({contentIdentity:'sha256:'+ '2'.repeat(64)})})};const a=await run(),b=await run();assert.equal(a.contentIdentity,b.contentIdentity);assert.notEqual(a.operationalId,b.operationalId)});
