import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { compileSource } from './fia-source-build.mjs';

const valid='<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width"><title>MC</title></head><body><main>Owned</main></body></html>';
async function fixture(script){const root=await mkdtemp(path.join(os.tmpdir(),'fia-source-test-'));await writeFile(path.join(root,'package-lock.json'),'{}\n');await writeFile(path.join(root,'build.mjs'),script);return root}
const cmd=['node','build.mjs'];
test('two clean builds produce one retained reproducibility authority',async()=>{const src=await fixture(`import{mkdir,writeFile}from'node:fs/promises';await mkdir('dist');await writeFile('dist/index.html',${JSON.stringify(valid)});await writeFile('dist/app.js','console.log("owned")\\n');console.log('built');`);const out=path.join(src,'out');const ev=await compileSource({source:src,output:out,command:cmd,sourceIdentity:'git:test'});assert.equal(ev.reproducible,true);assert.equal(ev.runs.length,2);assert.equal(ev.runs[0].releaseIdentity,ev.runs[1].releaseIdentity);await readFile(path.join(out,'release','manifest.json'));await readFile(path.join(out,'reproducibility.json'));await readFile(path.join(out,'build-1.stdout.log'))});
test('undeclared host environment is not inherited',async()=>{process.env.FIA_SECRET_LEAK='should-not-appear';const src=await fixture(`import{mkdir,writeFile}from'node:fs/promises';await mkdir('dist');await writeFile('dist/index.html',${JSON.stringify(valid)});await writeFile('dist/env.txt',String(process.env.FIA_SECRET_LEAK));`);const out=path.join(src,'out');await compileSource({source:src,output:out,command:cmd});const manifest=JSON.parse(await readFile(path.join(out,'release','manifest.json'),'utf8'));const envEntry=manifest.files.find(x=>x.path==='env.txt');assert.ok(envEntry);delete process.env.FIA_SECRET_LEAK});
test('provider-coupled output is rejected',async()=>{const src=await fixture(`import{mkdir,writeFile}from'node:fs/promises';await mkdir('dist');await writeFile('dist/index.html',${JSON.stringify(valid)});await writeFile('dist/app.js','fetch("https://x.pages.dev/api")');`);await assert.rejects(compileSource({source:src,output:path.join(src,'out'),command:cmd}),/provider coupling detected/)});
test('zero exit without declared output is false success',async()=>{const src=await fixture(`console.log('success but no artifact');`);await assert.rejects(compileSource({source:src,output:path.join(src,'out'),command:cmd}),/reported success without dist/)});
test('nondeterministic output is rejected',async()=>{const src=await fixture(`import{mkdir,writeFile}from'node:fs/promises';await mkdir('dist');await writeFile('dist/index.html',${JSON.stringify(valid)});await writeFile('dist/random.txt',String(Math.random()));`);await assert.rejects(compileSource({source:src,output:path.join(src,'out'),command:cmd}),/reproducibility mismatch/)});
test('missing lockfile and existing output fail before mutation',async()=>{const src=await mkdtemp(path.join(os.tmpdir(),'fia-source-test-'));await writeFile(path.join(src,'build.mjs'),'');await assert.rejects(compileSource({source:src,output:path.join(src,'out'),command:cmd}),/lockfile missing/);await writeFile(path.join(src,'package-lock.json'),'{}');await mkdir(path.join(src,'out'));await writeFile(path.join(src,'out','sentinel'),'keep');await assert.rejects(compileSource({source:src,output:path.join(src,'out'),command:cmd}),/output exists/);assert.equal(await readFile(path.join(src,'out','sentinel'),'utf8'),'keep')});
