export const MUSIC_COMPOSITION_SPEC = {
  form: ['seed', 'seed', 'lift', 'answer', 'storm', 'answer', 'lift', 'home'],
  motif: [0, 2, 3, 5, 3, 2, 6, 5, 3, 1, 2, 0, 5, 6, 3, 2],
  answer: [5, 3, 2, 0, 2, 3, 1, -1, 0, 2, 5, 3, 2, 0, -2, 0],
  bassWalk: [0, 0, 2, 4, 5, 5, 4, 2, 7, 7, 6, 5, 3, 2, 1, 0],
  weatherMeters: {
    cloud: 4,
    rain: 6,
    lightning: 5,
    clear: 4,
    aurora: 7,
    dawn: 4,
    wind: 3,
    murmur: 6,
  },
  arrangementProfiles: {
    seed: { melody: 0.82, bass: 0.72, harmony: 0.42, counter: 0, sparkle: 0, weather: 0.24 },
    lift: { melody: 1, bass: 0.86, harmony: 0.72, counter: 0.28, sparkle: 0.42, weather: 0.34 },
    answer: { melody: 0.72, bass: 0.64, harmony: 0.52, counter: 0.54, sparkle: 0.08, weather: 0.26 },
    storm: { melody: 1, bass: 0.9, harmony: 0.64, counter: 0.36, sparkle: 0.66, weather: 0.48 },
    home: { melody: 0.58, bass: 0.78, harmony: 0.76, counter: 0.18, sparkle: 0, weather: 0.16 },
  },
  weatherArticulation: {
    cloud: { melodyType: 'sine', chordType: 'triangle', toneFilter: 2100, bassFilter: 520, chordShift: 0, bassOctave: 0 },
    rain: { melodyType: 'sine', chordType: 'triangle', toneFilter: 1900, bassFilter: 480, chordShift: -12, bassOctave: 0 },
    lightning: { melodyType: 'triangle', chordType: 'triangle', toneFilter: 3800, bassFilter: 740, chordShift: 0, bassOctave: 0 },
    clear: { melodyType: 'sine', chordType: 'triangle', toneFilter: 2500, bassFilter: 560, chordShift: 0, bassOctave: 0 },
    aurora: { melodyType: 'triangle', chordType: 'sine', toneFilter: 4300, bassFilter: 620, chordShift: 12, bassOctave: 1 },
    dawn: { melodyType: 'triangle', chordType: 'triangle', toneFilter: 3600, bassFilter: 640, chordShift: 12, bassOctave: 0 },
    wind: { melodyType: 'sine', chordType: 'triangle', toneFilter: 3100, bassFilter: 680, chordShift: 0, bassOctave: 0 },
    murmur: { melodyType: 'triangle', chordType: 'sine', toneFilter: 3900, bassFilter: 600, chordShift: 12, bassOctave: 0 },
  },
  qualityGate: {
    scheduler: 'cap catch-up scheduling after mobile tab sleep so the engine never floods Web Audio with late events',
    density: 'make seed/home sections sparse, lift sections brighter, and storm sections narrower instead of stacking all layers',
    mix: 'lower rain noise, sparkle, and storm accent gain before the compressor so the limiter polishes rather than rescues overload',
    repetition: 'reserve upper sparkle for phrase endings only; avoid triggering it every small loop',
    mobile: 'preserve tap-to-start, no autoplay, no visible explanatory text, and no sampled assets',
  },
  connectorFinding: 'Full skyMusic.js replacement is still rejected by the GitHub connector safety layer. Smaller spec updates are accepted, so the next practical implementation path is surgical patching of constants and one helper at a time rather than whole-file replacement.',
  nextImplementationTarget: 'apply arrangementProfiles and weatherArticulation to skyMusic.js using small sequential edits: first import/spec constants, then gain scaling, then articulation, then sparkle/weather thinning',
};
