import React,{useEffect,useMemo,useRef,useState}from'react';
import{ROOMS,LAYERS_PER_ROOM,roomById}from'../world/roomCatalog';
import{createRoomAudio}from'../world/roomAudio';
import'./RoomWorld.css';
const TAU=Math.PI*2,KEY='mc-room-world-v3',clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v));
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}};
const rgba=(h,a)=>{const n=parseInt(h.slice(1),16);return`rgba(${n>>16},${n>>8&255},${n&255},${a})`};
const random=s=>()=>((s=(Math.imul(s,1664525)+1013904223)>>>0)/4294967296);
function poly(c,r,n,a=0){c.beginPath();for(let i=0;i<=n;i++){const q=a+i/n*TAU,x=Math.cos(q)*r,y=Math.sin(q)*r;i?c.lineTo(x,y):c.moveTo(x,y)}c.closePath()}
function layer(c,R,L,w,h,t,p,pulse){const q=random(L.seed),r=Math.min(w,h)*(.05+L.index*.021)*L.scale,n=4+Math.floor(L.density*12);c.save();c.translate(w/2+(p.x-.5)*w*.05*L.index/20,h/2+(p.y-.5)*h*.05*L.index/20);c.rotate(L.rotation+t*.000025*(R.gravity||.2));c.globalCompositeOperation=L.index%3?'screen':'lighter';c.strokeStyle=rgba(R.palette[2+L.index%2],.06+L.density*.1+pulse*.03);c.fillStyle=rgba(R.palette[2+L.index%2],.02+L.density*.03);c.lineWidth=.5+L.index%4*.25;if(['orbital','clock'].includes(L.form)){for(let i=0;i<n;i++){c.beginPath();c.arc(Math.cos(i/n*TAU+t*.0002)*r*.2,Math.sin(i/n*TAU+t*.0002)*r*.2,r*(.2+i/n*.8),0,TAU);c.stroke()}}else if(['tide','thread','choir'].includes(L.form)){for(let j=0;j<n;j++){c.beginPath();for(let i=0;i<50;i++){const x=-w*.55+i/49*w*1.1,y=Math.sin(i*.22+j*.7+t*.001+p.x*5)*r*.14+j*r*.04-r*.3;i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke()}}else if(['spore','garden','hive'].includes(L.form)){for(let i=0;i<n*2;i++){const a=q()*TAU,d=q()*r;c.beginPath();c.arc(Math.cos(a)*d,Math.sin(a)*d,1+q()*r*.05,0,TAU);i%3?c.stroke():c.fill()}}else if(['storm','ember'].includes(L.form)){for(let i=0;i<n;i++){c.beginPath();let x=0,y=0;c.moveTo(0,0);for(let k=0;k<9;k++){x+=(q()-.5)*r*.3;y+=(q()-.4)*r*.25;c.lineTo(x,y)}c.stroke()}}else{for(let i=0;i<n;i++){poly(c,r*(.16+i/n*.9),3+(i+R.portalShape)%7,i*.15);i%2?c.stroke():c.fill()}}c.restore()}
function Map({s,go,close}){return <div className="portal-map"><button className="map-close" onClick={close}>×</button><div className="portal-grid">{ROOMS.map(r=>{const o=s.unlocked.includes(r.id),v=s.visited.includes(r.id);return <button key={r.id} disabled={!o} className={`portal ${o?'open':''} ${v?'seen':''}`} style={{'--c':r.palette[2]}} onClick={()=>o&&go(r.id)}><i>{o?'◇':'·'}</i></button>})}</div></div>}
export default function RoomWorldRuntime(){const saved=read(),[s,setS]=useState(()=>({unlocked:[1],visited:[1],depth:{1:1},energy:0,gestures:{},...saved})),[id,setId]=useState(saved.roomId||1),[d,setD]=useState(saved.depth?.[saved.roomId||1]||1),[pulse,setPulse]=useState(.1),[map,setMap]=useState(false),[mute,setMute]=useState(false),room=useMemo(()=>roomById(id),[id]),canvas=useRef(null),point=useRef({x:.5,y:.5,down:false,sx:.5,sy:.5,at:0}),parts=useRef([]),audio=useRef(null);
useEffect(()=>{audio.current=createRoomAudio();return()=>audio.current?.dispose()},[]);useEffect(()=>localStorage.setItem(KEY,JSON.stringify({...s,roomId:id})),[s,id]);useEffect(()=>{const n=setInterval(()=>setPulse(v=>Math.max(.06,v*.96)),100);return()=>clearInterval(n)},[]);
useEffect(()=>{const el=canvas.current,c=el.getContext('2d');let af=0,start=performance.now();const size=()=>{const z=Math.min(2,devicePixelRatio||1),r=el.getBoundingClientRect();el.width=r.width*z;el.height=r.height*z;c.setTransform(z,0,0,z,0,0)};const frame=now=>{const r=el.getBoundingClientRect(),w=r.width,h=r.height,g=c.createRadialGradient(w*(.25+point.current.x*.5),h*(.2+point.current.y*.5),0,w/2,h/2,Math.max(w,h));g.addColorStop(0,room.palette[1]);g.addColorStop(.58,room.palette[0]);g.addColorStop(1,'#020207');c.globalCompositeOperation='source-over';c.fillStyle=g;c.fillRect(0,0,w,h);room.layers.slice(0,d).forEach(L=>layer(c,room,L,w,h,now-start,point.current,pulse));for(let i=parts.current.length-1;i>=0;i--){const p=parts.current[i];p.life-=.014;p.x+=p.vx;p.y+=p.vy;if(p.life<=0){parts.current.splice(i,1);continue}c.globalCompositeOperation='lighter';c.fillStyle=rgba(room.palette[2+i%2],p.life);c.beginPath();c.arc(p.x*w,p.y*h,1+p.life*7,0,TAU);c.fill()}af=requestAnimationFrame(frame)};size();addEventListener('resize',size);af=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(af);removeEventListener('resize',size)}},[room,d,pulse]);
const record=(boost,g)=>setS(old=>{const energy=old.energy+boost,u=new Set(old.unlocked);ROOMS.forEach(r=>{if(energy>=r.unlockCost)u.add(r.id)});const raw=(old.depth?.[id]||1)+boost*.8,next=Math.min(20,Math.max(d,Math.floor(raw)));setD(next);return{...old,energy,unlocked:[...u].sort((a,b)=>a-b),visited:[...new Set([...old.visited,id])],depth:{...old.depth,[id]:next},gestures:{...old.gestures,[id]:[...new Set([...(old.gestures?.[id]||[]),g])]}}});
const act=(e,type)=>{const r=e.currentTarget.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width),y=clamp((e.clientY-r.top)/r.height),p=point.current,now=performance.now(),dx=x-p.x,dy=y-p.y,speed=Math.hypot(dx,dy);let g='tap';if(type==='down')point.current={...p,x,y,down:true,sx:x,sy:y,at:now};else if(type==='move'){point.current={...p,x,y};g=speed>.055?'rapid':Math.abs(dx)>Math.abs(dy)?'trace':'fold'}else{const dist=Math.hypot(x-p.sx,y-p.sy);g=dist>.25?'sweep':now-p.at>650?'hold':'tap';point.current={...p,x,y,down:false}}const boost=type==='move'&&p.down?.06:type==='down'?.72:type==='up'?.4:.01;record(boost,g);setPulse(v=>Math.min(1,v+boost*.3));if(!mute){audio.current?.wake();g==='hold'?audio.current?.chord(room,room.layers[Math.max(0,d-1)],pulse):audio.current?.voice(room,room.layers[Math.max(0,d-1)],pulse,x,y)}for(let i=0;i<(type==='down'?15:2);i++)parts.current.push({x,y,vx:(Math.random()-.5)*.006,vy:(Math.random()-.5)*.006,life:.4+Math.random()*.6})};
const go=n=>{setId(n);setD(s.depth?.[n]||1);setMap(false);setS(v=>({...v,visited:[...new Set([...v.visited,n])]}))};
return <main className="room-world" style={{'--p0':room.palette[0],'--p1':room.palette[1],'--p2':room.palette[2],'--p3':room.palette[3]}}><button className="world-surface" onPointerDown={e=>act(e,'down')} onPointerMove={e=>act(e,'move')} onPointerUp={e=>act(e,'up')} onPointerCancel={e=>act(e,'up')}><canvas ref={canvas}/></button><div className="depth-spine">{Array.from({length:LAYERS_PER_ROOM},(_,i)=><i key={i} className={i<d?'lit':''}/>)}</div><button className="world-map-button" onClick={()=>setMap(true)}><span>✣</span><b>{s.unlocked.length}</b></button><button className={`sound-orb ${mute?'muted':''}`} onClick={()=>setMute(v=>{const n=!v;n?audio.current?.silence():audio.current?.wake();return n})}><i/><i/><i/></button><div className="room-sigil"><i/><span>{Array.from({length:Math.min(9,Math.ceil(id/12))},(_,i)=><b key={i}/>)}</span></div>{d===20&&<button className="completion-portal" onClick={()=>go(s.unlocked.find(n=>!s.visited.includes(n))||s.unlocked[(s.unlocked.indexOf(id)+1)%s.unlocked.length]||1)}><i/></button>}{map&&<Map s={s} go={go} close={()=>setMap(false)}/>}</main>}
