#!/usr/bin/env node
import fs from "node:fs";import os from "node:os";import path from "node:path";import {spawnSync} from "node:child_process";
const here=path.dirname(new URL(import.meta.url).pathname),policy=path.join(here,'policy.json'),base=JSON.parse(fs.readFileSync(path.join(here,'inventory.json'),'utf8')),v=path.join(here,'verify-release-deployment-contract.mjs');
const muts=[
['reject-scheduler-authority',x=>x.authority.scheduler_authoritative=true],['reject-git-authority',x=>x.authority.git_provider_authoritative=true],['reject-tag-authority',x=>x.authority.registry_tag_authoritative=true],['reject-fixed-adapter',x=>x.authority.adapter_replaceable=false],
['reject-tagged-artifact',x=>x.release.artifact='registry/app:latest'],['reject-one-signer',x=>x.release.release_signers=1],['reject-builder-release',x=>x.release.builder_can_release=true],['reject-registry-release',x=>x.release.registry_writer_can_release=true],['reject-deployer-signing',x=>x.release.deployer_can_sign=true],['reject-no-provenance',x=>x.release.provenance_verified=false],['reject-no-vsa',x=>x.release.verification_summary=false],['reject-no-sbom',x=>x.release.sbom=false],['reject-no-offline-bundle',x=>x.release.offline_bundle=false],['reject-transparency-only',x=>x.release.transparency_sole_path=true],['reject-no-rollback-protection',x=>x.release.rollback_attack_protection=false],
['reject-unsigned-desired-state',x=>x.deployment.desired_state_signed=false],['reject-artifact-mismatch',x=>x.deployment.artifact_digest_match=false],['reject-no-config-digest',x=>x.deployment.config_digest=''],['reject-one-domain',x=>x.deployment.failure_domains=['site-a']],['reject-no-canary',x=>x.deployment.canary=false],['reject-auto-promote',x=>x.deployment.automatic_promotion=true],['reject-health-only',x=>x.deployment.semantic_evidence=false],['reject-short-observation',x=>x.deployment.observation_seconds=30],['reject-large-batch',x=>x.deployment.max_parallel_percent=100],['reject-no-drain',x=>x.deployment.connection_draining=false],['reject-no-old-release',x=>x.deployment.previous_release_retained=false],['reject-scheduler-canonical',x=>x.deployment.scheduler_state_canonical=true],
['reject-no-rollback-manifest',x=>x.rollback.manifest=false],['reject-auto-data-rollback',x=>{x.rollback.change_class='schema-destructive';x.rollback.automatic_allowed=true}],['reject-db-incompatible',x=>x.rollback.database_compatible=false],['reject-queue-incompatible',x=>x.rollback.queue_compatible=false],['reject-unclassified-side-effects',x=>x.rollback.external_side_effects=''],['reject-floating-rollback',x=>x.rollback.target_digest='previous'],['reject-unverified-rollback',x=>x.rollback.target_reverified=false],['reject-one-data-operator',x=>x.rollback.data_rollback_operator_count=1],['reject-no-forward-fix',x=>x.rollback.forward_fix=false],
['reject-runtime-stages',x=>x.progressive_delivery.stages_source_controlled=false],['reject-missing-metrics-promote',x=>x.progressive_delivery.missing_metrics_fail_closed=false],['reject-no-baseline',x=>x.progressive_delivery.baseline_comparison=false],['reject-no-absolute-budget',x=>x.progressive_delivery.absolute_error_budget=false],['reject-tiny-sample',x=>x.progressive_delivery.minimum_sample_count=10],['reject-no-novel-failure',x=>x.progressive_delivery.novel_failure_detection=false],['reject-shared-promotion-credential',x=>x.progressive_delivery.promotion_credential_separate=false],
['reject-github-required',x=>x.continuity.github_required=true],['reject-registry-required',x=>x.continuity.original_registry_required=true],['reject-scheduler-required',x=>x.continuity.original_scheduler_required=true],['reject-no-offline-ledger',x=>x.continuity.offline_release_ledger=false],['reject-stale-recovery',x=>x.continuity.last_clean_host_recovery_age_days=31],['reject-one-operator',x=>x.continuity.trained_operators=1],['reject-unsigned-evidence',x=>x.evidence.signed=false],['reject-no-rollback-rehearsal',x=>x.evidence.rollback_rehearsal=false]
];
function run(x){const d=fs.mkdtempSync(path.join(os.tmpdir(),'rd-'));const f=path.join(d,'i.json');fs.writeFileSync(f,JSON.stringify(x));const r=spawnSync(process.execPath,[v,policy,f],{encoding:'utf8'});fs.rmSync(d,{recursive:true,force:true});return r}
let r=run(base);if(r.status){console.error(r.stdout,r.stderr);process.exit(1)}console.log('PASS baseline');for(const [n,m] of muts){const x=structuredClone(base);m(x);r=run(x);if(!r.status){console.error(`FAIL ${n}`);process.exit(1)}console.log(`PASS ${n}`)}console.log('PASS adversarial release/deployment controls');
