import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,symlink,unlink,readFile,readdir,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {request} from 'node:http';
import {startOwnedProcessRuntime,requestProcessReload} from './owned-runtime-process-handoff.mjs';

async function fixture(){const root=await mkdtemp(join(tmpdir(),'fia-process-'));await mkdir(join(root,'releases','old'),{recursive:true});await mkdir(join(root,'releases','new'),{recursive:true});await writeFile(join(root,'releases','old','index.html'),'old');await writeFile(join(root,'releases','new','index.html'),'new');await symlink('releases/old',join(root,'active'));await writeFile(join(root,'reload.secret'),'x'.repeat(32));return root}
function get(port,path='/'){return new Promise((ok,no)=>{const r=request({host:'127.0.0.1',port,path},res=>{const a=[];res.on('data',x=>a.push(x));res.on('end',()=>ok({status:res.statusCode,body:Buffer.concat(a).toString(),headers:res.headers}))});r.on('error',no);r.end()})}

test('supervisor routes new connections to new worker only after authenticated handoff',async()=>{const root=await fixture();const rt=await startOwnedProcessRuntime({runtimeRoot:root});try{const port=rt.httpAddress.port;assert.equal((await get(port)).body,'old');const before=JSON.parse((await get(port,'/.well-known/fia-generation')).body);await unlink(join(root,'active'));await symlink('releases/new',join(root,'active'));assert.equal((await get(port)).body,'old');const out=await requestProcessReload({socketPath:rt.socketPath,secretPath:join(root,'reload.secret'),expectedProcessGeneration:1,expectedReleaseId:'old',expectedTargetReleaseId:'new'});assert.equal(out.state.releaseId,'new');assert.notEqual(out.state.workerProcessId,before.workerProcessId);assert.equal((await get(port)).body,'new');const after=JSON.parse((await get(port,'/.well-known/fia-generation')).body);assert.equal(after.processGeneration,2);assert.equal(after.releaseId,'new')}finally{await rt.close()}});

test('wrong secret and stale generation are rejected',async()=>{const root=await fixture();const rt=await startOwnedProcessRuntime({runtimeRoot:root});try{await writeFile(join(root,'bad.secret'),'y'.repeat(32));await assert.rejects(()=>requestProcessReload({socketPath:rt.socketPath,secretPath:join(root,'bad.secret')}),/unauthorized/);await unlink(join(root,'active'));await symlink('releases/new',join(root,'active'));await assert.rejects(()=>requestProcessReload({socketPath:rt.socketPath,secretPath:join(root,'reload.secret'),expectedProcessGeneration:9}),/stale process generation/);assert.equal((await get(rt.httpAddress.port)).body,'old')}finally{await rt.close()}});

test('control socket is owner-only and evidence is retained',async()=>{const root=await fixture();const rt=await startOwnedProcessRuntime({runtimeRoot:root});try{assert.equal((await stat(rt.socketPath)).mode&0o777,0o600);await unlink(join(root,'active'));await symlink('releases/new',join(root,'active'));await requestProcessReload({socketPath:rt.socketPath,secretPath:join(root,'reload.secret')});const files=await readdir(join(root,'process-handoffs'));assert.equal(files.length,1);const ev=JSON.parse(await readFile(join(root,'process-handoffs',files[0]),'utf8'));assert.equal(ev.policy.supervisorOwnsListener,true);assert.equal(ev.policy.oldWorkerDrained,true);assert.notEqual(ev.processes.before,ev.processes.after)}finally{await rt.close()}});
