import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,symlink,rename,stat,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {startOwnedRuntime,requestReload} from './owned-runtime-generation.mjs';

async function fixture(){const root=await mkdtemp(join(tmpdir(),'fia-runtime-'));await mkdir(join(root,'releases','old'),{recursive:true});await mkdir(join(root,'releases','new'),{recursive:true});await writeFile(join(root,'releases','old','index.html'),'OLD');await writeFile(join(root,'releases','new','index.html'),'NEW');await symlink('releases/old',join(root,'active'));const secret=join(root,'reload.secret');await writeFile(secret,randomBytes(32),{mode:0o600});const svc=await startOwnedRuntime({runtimeRoot:root,secretPath:secret});const base=`http://127.0.0.1:${svc.httpAddress.port}`;return{root,secret,svc,base}}
async function swap(root,target){const tmp=join(root,'active.next');await symlink(`releases/${target}`,tmp);await rename(tmp,join(root,'active'))}

test('generation endpoint is process-bound and no-store',async()=>{const f=await fixture();try{const r=await fetch(`${f.base}/.well-known/fia-generation`);assert.equal(r.headers.get('cache-control'),'no-store, max-age=0');const j=await r.json();assert.equal(j.releaseId,'old');assert.equal(j.processId,process.pid);assert.equal(j.processGeneration,1);assert.ok(j.startupNonce)}finally{await f.svc.close()}});
test('pointer switch does not change served bytes until authenticated reload',async()=>{const f=await fixture();try{assert.equal(await (await fetch(f.base)).text(),'OLD');const before=await (await fetch(`${f.base}/.well-known/fia-generation`)).json();await swap(f.root,'new');assert.equal(await (await fetch(f.base)).text(),'OLD');const out=await requestReload({socketPath:f.svc.socketPath,secretPath:f.secret,expectedProcessGeneration:1,expectedReleaseId:'old',expectedTargetReleaseId:'new'});assert.equal(out.state.releaseId,'new');assert.equal(out.state.processGeneration,2);assert.notEqual(out.state.startupNonce,before.startupNonce);assert.equal(await (await fetch(f.base)).text(),'NEW');assert.equal((await readdir(join(f.root,'handoffs'))).length,1)}finally{await f.svc.close()}});
test('unauthorized reload is rejected',async()=>{const f=await fixture();try{await swap(f.root,'new');const bad=join(f.root,'bad.secret');await writeFile(bad,randomBytes(32));await assert.rejects(requestReload({socketPath:f.svc.socketPath,secretPath:bad}),/unauthorized reload/);assert.equal((await (await fetch(`${f.base}/.well-known/fia-generation`)).json()).releaseId,'old')}finally{await f.svc.close()}});
test('stale generation and target mismatch are rejected',async()=>{const f=await fixture();try{await swap(f.root,'new');await assert.rejects(requestReload({socketPath:f.svc.socketPath,secretPath:f.secret,expectedProcessGeneration:2}),/stale process generation/);await assert.rejects(requestReload({socketPath:f.svc.socketPath,secretPath:f.secret,expectedProcessGeneration:1,expectedTargetReleaseId:'other'}),/active target release mismatch/)}finally{await f.svc.close()}});
test('reload socket is owner-only',async()=>{const f=await fixture();try{assert.equal((await stat(f.svc.socketPath)).mode&0o777,0o600)}finally{await f.svc.close()}});
test('release authority rejects symlinks during reload',async()=>{const f=await fixture();try{await symlink('/etc/passwd',join(f.root,'releases','new','leak'));await swap(f.root,'new');await assert.rejects(requestReload({socketPath:f.svc.socketPath,secretPath:f.secret,expectedProcessGeneration:1}),/symbolic link forbidden/);assert.equal((await (await fetch(`${f.base}/.well-known/fia-generation`)).json()).releaseId,'old')}finally{await f.svc.close()}});
